set_global_assignment -name FAMILY "Stratix V"
set_global_assignment -name DEVICE 5SGXEABN2F45C2
set_global_assignment -name ORIGINAL_QUARTUS_VERSION 11.1
set_global_assignment -name PROJECT_CREATION_TIME_DATE "19:16:12  OCTOBER 24, 2011"
set_global_assignment -name LAST_QUARTUS_VERSION "16.1.2 Standard Edition"
set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0
set_global_assignment -name MAX_CORE_JUNCTION_TEMP 85
set_global_assignment -name DEVICE_FILTER_PIN_COUNT 1932
set_global_assignment -name DEVICE_FILTER_SPEED_GRADE 2_H2
set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 256
set_global_assignment -name PARTITION_NETLIST_TYPE SOURCE -section_id Top
set_global_assignment -name PARTITION_FITTER_PRESERVATION_LEVEL PLACEMENT_AND_ROUTING -section_id Top
set_global_assignment -name PARTITION_COLOR 16764057 -section_id Top
set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "2.5 V"
set_global_assignment -name USE_CONFIGURATION_DEVICE ON
set_global_assignment -name CRC_ERROR_OPEN_DRAIN ON
set_global_assignment -name RESERVE_ALL_UNUSED_PINS_WEAK_PULLUP "AS INPUT TRI-STATED"
set_global_assignment -name OUTPUT_IO_TIMING_NEAR_END_VMEAS "HALF VCCIO" -rise
set_global_assignment -name OUTPUT_IO_TIMING_NEAR_END_VMEAS "HALF VCCIO" -fall
set_global_assignment -name OUTPUT_IO_TIMING_FAR_END_VMEAS "HALF SIGNAL SWING" -rise
set_global_assignment -name OUTPUT_IO_TIMING_FAR_END_VMEAS "HALF SIGNAL SWING" -fall
set_global_assignment -name ACTIVE_SERIAL_CLOCK FREQ_100MHZ

set_location_assignment PIN_BC34 -to clkinbota_ddr3_n
set_location_assignment PIN_BB33 -to clkinbota_ddr3_p
set_location_assignment PIN_M25  -to clkintopa_ddr3_n
set_location_assignment PIN_N25  -to clkintopa_ddr3_p
set_location_assignment PIN_AR35 -to clock_scl
set_location_assignment PIN_AR36 -to clock_sda
set_location_assignment PIN_BC20 -to ddr3a_a[0]
set_location_assignment PIN_AP21 -to ddr3a_a[1]
set_location_assignment PIN_AR22 -to ddr3a_a[2]
set_location_assignment PIN_BA22 -to ddr3a_a[3]
set_location_assignment PIN_AY21 -to ddr3a_a[4]
set_location_assignment PIN_AY22 -to ddr3a_a[5]
set_location_assignment PIN_AV20 -to ddr3a_a[6]
set_location_assignment PIN_AW21 -to ddr3a_a[7]
set_location_assignment PIN_AU22 -to ddr3a_a[8]
set_location_assignment PIN_BD22 -to ddr3a_a[9]
set_location_assignment PIN_AU20 -to ddr3a_a[10]
set_location_assignment PIN_BC22 -to ddr3a_a[11]
set_location_assignment PIN_AW20 -to ddr3a_a[12]
set_location_assignment PIN_AT21 -to ddr3a_a[13]
set_location_assignment PIN_BA21 -to ddr3a_ba[0]
set_location_assignment PIN_BD20 -to ddr3a_ba[1]
set_location_assignment PIN_AU21 -to ddr3a_ba[2]
set_location_assignment PIN_AK20 -to ddr3a_casn
set_location_assignment PIN_AT20 -to ddr3a_cke
set_location_assignment PIN_AW22 -to ddr3a_clk_n
set_location_assignment PIN_AV22 -to ddr3a_clk_p
set_location_assignment PIN_BB21 -to ddr3a_csn
set_location_assignment PIN_BB23 -to ddr3a_dm[0]
set_location_assignment PIN_AN22 -to ddr3a_dm[1]
set_location_assignment PIN_AU25 -to ddr3a_dm[2]
set_location_assignment PIN_AL21 -to ddr3a_dm[3]
set_location_assignment PIN_AT24 -to ddr3a_dq[0]
set_location_assignment PIN_AW23 -to ddr3a_dq[1]
set_location_assignment PIN_AV23 -to ddr3a_dq[2]
set_location_assignment PIN_AU23 -to ddr3a_dq[3]
set_location_assignment PIN_BC23 -to ddr3a_dq[4]
set_location_assignment PIN_BB24 -to ddr3a_dq[5]
set_location_assignment PIN_AY24 -to ddr3a_dq[6]
set_location_assignment PIN_BD23 -to ddr3a_dq[7]
set_location_assignment PIN_AJ21 -to ddr3a_dq[8]
set_location_assignment PIN_AM20 -to ddr3a_dq[9]
set_location_assignment PIN_AJ19 -to ddr3a_dq[10]
set_location_assignment PIN_AM22 -to ddr3a_dq[11]
set_location_assignment PIN_AG19 -to ddr3a_dq[12]
set_location_assignment PIN_AL20 -to ddr3a_dq[13]
set_location_assignment PIN_AG20 -to ddr3a_dq[14]
set_location_assignment PIN_AJ20 -to ddr3a_dq[15]
set_location_assignment PIN_AR25 -to ddr3a_dq[16]
set_location_assignment PIN_AV25 -to ddr3a_dq[17]
set_location_assignment PIN_AW24 -to ddr3a_dq[18]
set_location_assignment PIN_AU24 -to ddr3a_dq[19]
set_location_assignment PIN_BD26 -to ddr3a_dq[20]
set_location_assignment PIN_AY25 -to ddr3a_dq[21]
set_location_assignment PIN_BA24 -to ddr3a_dq[22]
set_location_assignment PIN_BC26 -to ddr3a_dq[23]
set_location_assignment PIN_AL23 -to ddr3a_dq[24]
set_location_assignment PIN_AK23 -to ddr3a_dq[25]
set_location_assignment PIN_AL24 -to ddr3a_dq[26]
set_location_assignment PIN_AK21 -to ddr3a_dq[27]
set_location_assignment PIN_AM23 -to ddr3a_dq[28]
set_location_assignment PIN_AJ22 -to ddr3a_dq[29]
set_location_assignment PIN_AN23 -to ddr3a_dq[30]
set_location_assignment PIN_AJ23 -to ddr3a_dq[31]
set_location_assignment PIN_BD25 -to ddr3a_dqs_n[0]
set_location_assignment PIN_AH21 -to ddr3a_dqs_n[1]
set_location_assignment PIN_BB26 -to ddr3a_dqs_n[2]
set_location_assignment PIN_AT23 -to ddr3a_dqs_n[3]
set_location_assignment PIN_BC25 -to ddr3a_dqs_p[0]
set_location_assignment PIN_AG21 -to ddr3a_dqs_p[1]
set_location_assignment PIN_BA25 -to ddr3a_dqs_p[2]
set_location_assignment PIN_AR23 -to ddr3a_dqs_p[3]
set_location_assignment PIN_AR20 -to ddr3a_odt
set_location_assignment PIN_AR21 -to ddr3a_rasn
set_location_assignment PIN_AR24 -to ddr3a_resetn
set_location_assignment PIN_BB20 -to ddr3a_wen
set_location_assignment PIN_AJ32 -to ddr3b_a[0]
set_location_assignment PIN_AM32 -to ddr3b_a[1]
set_location_assignment PIN_AR31 -to ddr3b_a[2]
set_location_assignment PIN_AG33 -to ddr3b_a[3]
set_location_assignment PIN_AE29 -to ddr3b_a[4]
set_location_assignment PIN_AE33 -to ddr3b_a[5]
set_location_assignment PIN_AJ33 -to ddr3b_a[6]
set_location_assignment PIN_AF34 -to ddr3b_a[7]
set_location_assignment PIN_AD33 -to ddr3b_a[8]
set_location_assignment PIN_AN31 -to ddr3b_a[9]
set_location_assignment PIN_AR32 -to ddr3b_a[10]
set_location_assignment PIN_AP31 -to ddr3b_a[11]
set_location_assignment PIN_AN33 -to ddr3b_a[12]
set_location_assignment PIN_AM31 -to ddr3b_a[13]
set_location_assignment PIN_AH33 -to ddr3b_ba[0]
set_location_assignment PIN_AK33 -to ddr3b_ba[1]
set_location_assignment PIN_AK32 -to ddr3b_ba[2]
set_location_assignment PIN_AE30 -to ddr3b_casn
set_location_assignment PIN_AG32 -to ddr3b_cke
set_location_assignment PIN_AE32 -to ddr3b_clk_n
set_location_assignment PIN_AD32 -to ddr3b_clk_p
set_location_assignment PIN_AF32 -to ddr3b_csn
set_location_assignment PIN_BC31 -to ddr3b_dm[0]
set_location_assignment PIN_AK24 -to ddr3b_dm[1]
set_location_assignment PIN_AN30 -to ddr3b_dm[2]
set_location_assignment PIN_AG29 -to ddr3b_dm[3]
set_location_assignment PIN_AV29 -to ddr3b_dm[4]
set_location_assignment PIN_AV32 -to ddr3b_dm[5]
set_location_assignment PIN_AV26 -to ddr3b_dm[6]
set_location_assignment PIN_BA27 -to ddr3b_dm[7]
set_location_assignment PIN_AW30 -to ddr3b_dq[0]
set_location_assignment PIN_BB30 -to ddr3b_dq[1]
set_location_assignment PIN_BD31 -to ddr3b_dq[2]
set_location_assignment PIN_BC32 -to ddr3b_dq[3]
set_location_assignment PIN_BB32 -to ddr3b_dq[4]
set_location_assignment PIN_AY31 -to ddr3b_dq[5]
set_location_assignment PIN_BD32 -to ddr3b_dq[6]
set_location_assignment PIN_BA30 -to ddr3b_dq[7]
set_location_assignment PIN_AH24 -to ddr3b_dq[8]
set_location_assignment PIN_AJ24 -to ddr3b_dq[9]
set_location_assignment PIN_AH28 -to ddr3b_dq[10]
set_location_assignment PIN_AK26 -to ddr3b_dq[11]
set_location_assignment PIN_AJ28 -to ddr3b_dq[12]
set_location_assignment PIN_AL26 -to ddr3b_dq[13]
set_location_assignment PIN_AH25 -to ddr3b_dq[14]
set_location_assignment PIN_AJ27 -to ddr3b_dq[15]
set_location_assignment PIN_AR30 -to ddr3b_dq[16]
set_location_assignment PIN_AP30 -to ddr3b_dq[17]
set_location_assignment PIN_AU32 -to ddr3b_dq[18]
set_location_assignment PIN_AT30 -to ddr3b_dq[19]
set_location_assignment PIN_AH30 -to ddr3b_dq[20]
set_location_assignment PIN_AH31 -to ddr3b_dq[21]
set_location_assignment PIN_AJ30 -to ddr3b_dq[22]
set_location_assignment PIN_AJ31 -to ddr3b_dq[23]
set_location_assignment PIN_AG27 -to ddr3b_dq[24]
set_location_assignment PIN_AG28 -to ddr3b_dq[25]
set_location_assignment PIN_AG25 -to ddr3b_dq[26]
set_location_assignment PIN_AG30 -to ddr3b_dq[27]
set_location_assignment PIN_AF28 -to ddr3b_dq[28]
set_location_assignment PIN_AK29 -to ddr3b_dq[29]
set_location_assignment PIN_AG26 -to ddr3b_dq[30]
set_location_assignment PIN_AF29 -to ddr3b_dq[31]
set_location_assignment PIN_AL28 -to ddr3b_dq[32]
set_location_assignment PIN_AU28 -to ddr3b_dq[33]
set_location_assignment PIN_AU29 -to ddr3b_dq[34]
set_location_assignment PIN_AM28 -to ddr3b_dq[35]
set_location_assignment PIN_AP27 -to ddr3b_dq[36]
set_location_assignment PIN_AK27 -to ddr3b_dq[37]
set_location_assignment PIN_AV28 -to ddr3b_dq[38]
set_location_assignment PIN_AL27 -to ddr3b_dq[39]
set_location_assignment PIN_AR29 -to ddr3b_dq[40]
set_location_assignment PIN_AU31 -to ddr3b_dq[41]
set_location_assignment PIN_AM29 -to ddr3b_dq[42]
set_location_assignment PIN_AW32 -to ddr3b_dq[43]
set_location_assignment PIN_AP28 -to ddr3b_dq[44]
set_location_assignment PIN_AV31 -to ddr3b_dq[45]
set_location_assignment PIN_AN28 -to ddr3b_dq[46]
set_location_assignment PIN_AU30 -to ddr3b_dq[47]
set_location_assignment PIN_AN25 -to ddr3b_dq[48]
set_location_assignment PIN_AU27 -to ddr3b_dq[49]
set_location_assignment PIN_AM25 -to ddr3b_dq[50]
set_location_assignment PIN_AW26 -to ddr3b_dq[51]
set_location_assignment PIN_AL25 -to ddr3b_dq[52]
set_location_assignment PIN_AR26 -to ddr3b_dq[53]
set_location_assignment PIN_AT27 -to ddr3b_dq[54]
set_location_assignment PIN_AM26 -to ddr3b_dq[55]
set_location_assignment PIN_BD29 -to ddr3b_dq[56]
set_location_assignment PIN_BB27 -to ddr3b_dq[57]
set_location_assignment PIN_BB29 -to ddr3b_dq[58]
set_location_assignment PIN_AW29 -to ddr3b_dq[59]
set_location_assignment PIN_AY28 -to ddr3b_dq[60]
set_location_assignment PIN_AW27 -to ddr3b_dq[61]
set_location_assignment PIN_BA28 -to ddr3b_dq[62]
set_location_assignment PIN_AY27 -to ddr3b_dq[63]
set_location_assignment PIN_BA29 -to ddr3b_dqs_n[0]
set_location_assignment PIN_AJ26 -to ddr3b_dqs_n[1]
set_location_assignment PIN_AL31 -to ddr3b_dqs_n[2]
set_location_assignment PIN_AE28 -to ddr3b_dqs_n[3]
set_location_assignment PIN_AR28 -to ddr3b_dqs_n[4]
set_location_assignment PIN_AL29 -to ddr3b_dqs_n[5]
set_location_assignment PIN_AU26 -to ddr3b_dqs_n[6]
set_location_assignment PIN_BD28 -to ddr3b_dqs_n[7]
set_location_assignment PIN_AY30 -to ddr3b_dqs_p[0]
set_location_assignment PIN_AJ25 -to ddr3b_dqs_p[1]
set_location_assignment PIN_AL30 -to ddr3b_dqs_p[2]
set_location_assignment PIN_AE27 -to ddr3b_dqs_p[3]
set_location_assignment PIN_AR27 -to ddr3b_dqs_p[4]
set_location_assignment PIN_AK30 -to ddr3b_dqs_p[5]
set_location_assignment PIN_AT26 -to ddr3b_dqs_p[6]
set_location_assignment PIN_BC28 -to ddr3b_dqs_p[7]
set_location_assignment PIN_AE31 -to ddr3b_odt
set_location_assignment PIN_AF31 -to ddr3b_rasn
set_location_assignment PIN_AE34 -to ddr3b_resetn
set_location_assignment PIN_AP33 -to ddr3b_wen
set_location_assignment PIN_G28  -to ddr3c_a[0]
set_location_assignment PIN_A26  -to ddr3c_a[1]
set_location_assignment PIN_C27  -to ddr3c_a[2]
set_location_assignment PIN_T27  -to ddr3c_a[3]
set_location_assignment PIN_G26  -to ddr3c_a[4]
set_location_assignment PIN_K28  -to ddr3c_a[5]
set_location_assignment PIN_H27  -to ddr3c_a[6]
set_location_assignment PIN_J28  -to ddr3c_a[7]
set_location_assignment PIN_F26  -to ddr3c_a[8]
set_location_assignment PIN_B26  -to ddr3c_a[9]
set_location_assignment PIN_A28  -to ddr3c_a[10]
set_location_assignment PIN_D27  -to ddr3c_a[11]
set_location_assignment PIN_F28  -to ddr3c_a[12]
set_location_assignment PIN_E27  -to ddr3c_a[13]
set_location_assignment PIN_F29  -to ddr3c_ba[0]
set_location_assignment PIN_P26  -to ddr3c_ba[1]
set_location_assignment PIN_B28  -to ddr3c_ba[2]
set_location_assignment PIN_A29  -to ddr3c_casn
set_location_assignment PIN_H29  -to ddr3c_cke
set_location_assignment PIN_H26  -to ddr3c_clk_n
set_location_assignment PIN_J27  -to ddr3c_clk_p
set_location_assignment PIN_E29  -to ddr3c_csn
set_location_assignment PIN_D24  -to ddr3c_dm[0]
set_location_assignment PIN_P29  -to ddr3c_dm[1]
set_location_assignment PIN_D26  -to ddr3c_dm[2]
set_location_assignment PIN_U23  -to ddr3c_dm[3]
set_location_assignment PIN_E23  -to ddr3c_dq[0]
set_location_assignment PIN_D23  -to ddr3c_dq[1]
set_location_assignment PIN_B25  -to ddr3c_dq[2]
set_location_assignment PIN_E24  -to ddr3c_dq[3]
set_location_assignment PIN_B23  -to ddr3c_dq[4]
set_location_assignment PIN_F23  -to ddr3c_dq[5]
set_location_assignment PIN_A23  -to ddr3c_dq[6]
set_location_assignment PIN_A25  -to ddr3c_dq[7]
set_location_assignment PIN_P27  -to ddr3c_dq[8]
set_location_assignment PIN_M28  -to ddr3c_dq[9]
set_location_assignment PIN_M27  -to ddr3c_dq[10]
set_location_assignment PIN_N28  -to ddr3c_dq[11]
set_location_assignment PIN_L26  -to ddr3c_dq[12]
set_location_assignment PIN_P28  -to ddr3c_dq[13]
set_location_assignment PIN_N26  -to ddr3c_dq[14]
set_location_assignment PIN_R27  -to ddr3c_dq[15]
set_location_assignment PIN_E26  -to ddr3c_dq[16]
set_location_assignment PIN_F24  -to ddr3c_dq[17]
set_location_assignment PIN_F25  -to ddr3c_dq[18]
set_location_assignment PIN_H24  -to ddr3c_dq[19]
set_location_assignment PIN_J25  -to ddr3c_dq[20]
set_location_assignment PIN_J24  -to ddr3c_dq[21]
set_location_assignment PIN_G25  -to ddr3c_dq[22]
set_location_assignment PIN_H23  -to ddr3c_dq[23]
set_location_assignment PIN_N23  -to ddr3c_dq[24]
set_location_assignment PIN_L23  -to ddr3c_dq[25]
set_location_assignment PIN_T23  -to ddr3c_dq[26]
set_location_assignment PIN_K24  -to ddr3c_dq[27]
set_location_assignment PIN_U24  -to ddr3c_dq[28]
set_location_assignment PIN_L24  -to ddr3c_dq[29]
set_location_assignment PIN_T24  -to ddr3c_dq[30]
set_location_assignment PIN_M23  -to ddr3c_dq[31]
set_location_assignment PIN_C24  -to ddr3c_dqs_n[0]
set_location_assignment PIN_K27  -to ddr3c_dqs_n[1]
set_location_assignment PIN_K25  -to ddr3c_dqs_n[2]
set_location_assignment PIN_P24  -to ddr3c_dqs_n[3]
set_location_assignment PIN_C25  -to ddr3c_dqs_p[0]
set_location_assignment PIN_L27  -to ddr3c_dqs_p[1]
set_location_assignment PIN_K26  -to ddr3c_dqs_p[2]
set_location_assignment PIN_R24  -to ddr3c_dqs_p[3]
set_location_assignment PIN_G29  -to ddr3c_odt
set_location_assignment PIN_D29  -to ddr3c_rasn
set_location_assignment PIN_H28  -to ddr3c_resetn
set_location_assignment PIN_C28  -to ddr3c_wen
set_location_assignment PIN_J19  -to ddr3d_a[0]
set_location_assignment PIN_E17  -to ddr3d_a[1]
set_location_assignment PIN_K18  -to ddr3d_a[2]
set_location_assignment PIN_L18  -to ddr3d_a[3]
set_location_assignment PIN_D18  -to ddr3d_a[4]
set_location_assignment PIN_M18  -to ddr3d_a[5]
set_location_assignment PIN_B17  -to ddr3d_a[6]
set_location_assignment PIN_B19  -to ddr3d_a[7]
set_location_assignment PIN_H19  -to ddr3d_a[8]
set_location_assignment PIN_C18  -to ddr3d_a[9]
set_location_assignment PIN_N17  -to ddr3d_a[10]
set_location_assignment PIN_E18  -to ddr3d_a[11]
set_location_assignment PIN_M17  -to ddr3d_a[12]
set_location_assignment PIN_A17  -to ddr3d_a[13]
set_location_assignment PIN_K17  -to ddr3d_ba[0]
set_location_assignment PIN_L17  -to ddr3d_ba[1]
set_location_assignment PIN_H17  -to ddr3d_ba[2]
set_location_assignment PIN_P17  -to ddr3d_casn
set_location_assignment PIN_H16  -to ddr3d_cke
set_location_assignment PIN_P18  -to ddr3d_clk_n
set_location_assignment PIN_P19  -to ddr3d_clk_p
set_location_assignment PIN_R19  -to ddr3d_csn
set_location_assignment PIN_F22  -to ddr3d_dm[0]
set_location_assignment PIN_L21  -to ddr3d_dm[1]
set_location_assignment PIN_V19  -to ddr3d_dm[2]
set_location_assignment PIN_W18  -to ddr3d_dm[3]
set_location_assignment PIN_H14  -to ddr3d_dm[4]
set_location_assignment PIN_P16  -to ddr3d_dm[5]
set_location_assignment PIN_U15  -to ddr3d_dm[6]
set_location_assignment PIN_C13  -to ddr3d_dm[7]
set_location_assignment PIN_A20  -to ddr3d_dq[0]
set_location_assignment PIN_C21  -to ddr3d_dq[1]
set_location_assignment PIN_B20  -to ddr3d_dq[2]
set_location_assignment PIN_E20  -to ddr3d_dq[3]
set_location_assignment PIN_B22  -to ddr3d_dq[4]
set_location_assignment PIN_F21  -to ddr3d_dq[5]
set_location_assignment PIN_A22  -to ddr3d_dq[6]
set_location_assignment PIN_E21  -to ddr3d_dq[7]
set_location_assignment PIN_F20  -to ddr3d_dq[8]
set_location_assignment PIN_J21  -to ddr3d_dq[9]
set_location_assignment PIN_G20  -to ddr3d_dq[10]
set_location_assignment PIN_J22  -to ddr3d_dq[11]
set_location_assignment PIN_K21  -to ddr3d_dq[12]
set_location_assignment PIN_K22  -to ddr3d_dq[13]
set_location_assignment PIN_K20  -to ddr3d_dq[14]
set_location_assignment PIN_G22  -to ddr3d_dq[15]
set_location_assignment PIN_P21  -to ddr3d_dq[16]
set_location_assignment PIN_M22  -to ddr3d_dq[17]
set_location_assignment PIN_R21  -to ddr3d_dq[18]
set_location_assignment PIN_R22  -to ddr3d_dq[19]
set_location_assignment PIN_T21  -to ddr3d_dq[20]
set_location_assignment PIN_T22  -to ddr3d_dq[21]
set_location_assignment PIN_U20  -to ddr3d_dq[22]
set_location_assignment PIN_U21  -to ddr3d_dq[23]
set_location_assignment PIN_N20  -to ddr3d_dq[24]
set_location_assignment PIN_U18  -to ddr3d_dq[25]
set_location_assignment PIN_M20  -to ddr3d_dq[26]
set_location_assignment PIN_V18  -to ddr3d_dq[27]
set_location_assignment PIN_L20  -to ddr3d_dq[28]
set_location_assignment PIN_T18  -to ddr3d_dq[29]
set_location_assignment PIN_K19  -to ddr3d_dq[30]
set_location_assignment PIN_P20  -to ddr3d_dq[31]
set_location_assignment PIN_G14  -to ddr3d_dq[32]
set_location_assignment PIN_F13  -to ddr3d_dq[33]
set_location_assignment PIN_H13  -to ddr3d_dq[34]
set_location_assignment PIN_G13  -to ddr3d_dq[35]
set_location_assignment PIN_K16  -to ddr3d_dq[36]
set_location_assignment PIN_K13  -to ddr3d_dq[37]
set_location_assignment PIN_J13  -to ddr3d_dq[38]
set_location_assignment PIN_J16  -to ddr3d_dq[39]
set_location_assignment PIN_M14  -to ddr3d_dq[40]
set_location_assignment PIN_N16  -to ddr3d_dq[41]
set_location_assignment PIN_L14  -to ddr3d_dq[42]
set_location_assignment PIN_T16  -to ddr3d_dq[43]
set_location_assignment PIN_M15  -to ddr3d_dq[44]
set_location_assignment PIN_T17  -to ddr3d_dq[45]
set_location_assignment PIN_J15  -to ddr3d_dq[46]
set_location_assignment PIN_R16  -to ddr3d_dq[47]
set_location_assignment PIN_P15  -to ddr3d_dq[48]
set_location_assignment PIN_V15  -to ddr3d_dq[49]
set_location_assignment PIN_V13  -to ddr3d_dq[50]
set_location_assignment PIN_T15  -to ddr3d_dq[51]
set_location_assignment PIN_W14  -to ddr3d_dq[52]
set_location_assignment PIN_Y17  -to ddr3d_dq[53]
set_location_assignment PIN_V16  -to ddr3d_dq[54]
set_location_assignment PIN_W17  -to ddr3d_dq[55]
set_location_assignment PIN_C15  -to ddr3d_dq[56]
set_location_assignment PIN_B13  -to ddr3d_dq[57]
set_location_assignment PIN_D14  -to ddr3d_dq[58]
set_location_assignment PIN_B14  -to ddr3d_dq[59]
set_location_assignment PIN_E14  -to ddr3d_dq[60]
set_location_assignment PIN_A14  -to ddr3d_dq[61]
set_location_assignment PIN_F14  -to ddr3d_dq[62]
set_location_assignment PIN_A13  -to ddr3d_dq[63]
set_location_assignment PIN_D20  -to ddr3d_dqs_n[0]
set_location_assignment PIN_H20  -to ddr3d_dqs_n[1]
set_location_assignment PIN_V20  -to ddr3d_dqs_n[2]
set_location_assignment PIN_T19  -to ddr3d_dqs_n[3]
set_location_assignment PIN_K14  -to ddr3d_dqs_n[4]
set_location_assignment PIN_U17  -to ddr3d_dqs_n[5]
set_location_assignment PIN_W16  -to ddr3d_dqs_n[6]
set_location_assignment PIN_D15  -to ddr3d_dqs_n[7]
set_location_assignment PIN_D21  -to ddr3d_dqs_p[0]
set_location_assignment PIN_H21  -to ddr3d_dqs_p[1]
set_location_assignment PIN_V21  -to ddr3d_dqs_p[2]
set_location_assignment PIN_T20  -to ddr3d_dqs_p[3]
set_location_assignment PIN_L15  -to ddr3d_dqs_p[4]
set_location_assignment PIN_V17  -to ddr3d_dqs_p[5]
set_location_assignment PIN_Y16  -to ddr3d_dqs_p[6]
set_location_assignment PIN_E15  -to ddr3d_dqs_p[7]
set_location_assignment PIN_R18  -to ddr3d_odt
set_location_assignment PIN_G17  -to ddr3d_rasn
set_location_assignment PIN_A19  -to ddr3d_resetn
set_location_assignment PIN_F17  -to ddr3d_wen
set_location_assignment PIN_AR9  -to eeprom1_scl
set_location_assignment PIN_AP9  -to eeprom1_sda
set_location_assignment PIN_H18  -to fmc_clk_m2c_n[0]
set_location_assignment PIN_L9   -to fmc_clk_m2c_n[1]
set_location_assignment PIN_J18  -to fmc_clk_m2c_p[0]
set_location_assignment PIN_M9   -to fmc_clk_m2c_p[1]
set_location_assignment PIN_BD7  -to fmc_ga[0]
set_location_assignment PIN_BC7  -to fmc_ga[1]
set_location_assignment PIN_L8   -to fmc_la_rx_clk_n[0]
set_location_assignment PIN_A8   -to fmc_la_rx_clk_n[1]
set_location_assignment PIN_M8   -to fmc_la_rx_clk_p[0]
set_location_assignment PIN_B8   -to fmc_la_rx_clk_p[1]
set_location_assignment PIN_H10  -to fmc_la_rx_n[0]
set_location_assignment PIN_T11  -to fmc_la_rx_n[1]
set_location_assignment PIN_H8   -to fmc_la_rx_n[2]
set_location_assignment PIN_V9   -to fmc_la_rx_n[3]
set_location_assignment PIN_F10  -to fmc_la_rx_n[4]
set_location_assignment PIN_V11  -to fmc_la_rx_n[5]
set_location_assignment PIN_F8   -to fmc_la_rx_n[6]
set_location_assignment PIN_N13  -to fmc_la_rx_n[7]
set_location_assignment PIN_D9   -to fmc_la_rx_n[8]
set_location_assignment PIN_C12  -to fmc_la_rx_n[9]
set_location_assignment PIN_A11  -to fmc_la_rx_n[10]
set_location_assignment PIN_N14  -to fmc_la_rx_n[11]
set_location_assignment PIN_F11  -to fmc_la_rx_n[12]
set_location_assignment PIN_L11  -to fmc_la_rx_n[13]
set_location_assignment PIN_T9   -to fmc_la_rx_n[14]
set_location_assignment PIN_J10  -to fmc_la_rx_p[0]
set_location_assignment PIN_T12  -to fmc_la_rx_p[1]
set_location_assignment PIN_H9   -to fmc_la_rx_p[2]
set_location_assignment PIN_V10  -to fmc_la_rx_p[3]
set_location_assignment PIN_G10  -to fmc_la_rx_p[4]
set_location_assignment PIN_V12  -to fmc_la_rx_p[5]
set_location_assignment PIN_G8   -to fmc_la_rx_p[6]
set_location_assignment PIN_P13  -to fmc_la_rx_p[7]
set_location_assignment PIN_E8   -to fmc_la_rx_p[8]
set_location_assignment PIN_D12  -to fmc_la_rx_p[9]
set_location_assignment PIN_B11  -to fmc_la_rx_p[10]
set_location_assignment PIN_P14  -to fmc_la_rx_p[11]
set_location_assignment PIN_G11  -to fmc_la_rx_p[12]
set_location_assignment PIN_K11  -to fmc_la_rx_p[13]
set_location_assignment PIN_U9   -to fmc_la_rx_p[14]
set_location_assignment PIN_E9   -to fmc_la_tx_n[0]
set_location_assignment PIN_C10  -to fmc_la_tx_n[1]
set_location_assignment PIN_J12  -to fmc_la_tx_n[2]
set_location_assignment PIN_C9   -to fmc_la_tx_n[3]
set_location_assignment PIN_J9   -to fmc_la_tx_n[4]
set_location_assignment PIN_A7   -to fmc_la_tx_n[5]
set_location_assignment PIN_K9   -to fmc_la_tx_n[6]
set_location_assignment PIN_R10  -to fmc_la_tx_n[7]
set_location_assignment PIN_L12  -to fmc_la_tx_n[8]
set_location_assignment PIN_E11  -to fmc_la_tx_n[9]
set_location_assignment PIN_H11  -to fmc_la_tx_n[10]
set_location_assignment PIN_N8   -to fmc_la_tx_n[11]
set_location_assignment PIN_U11  -to fmc_la_tx_n[12]
set_location_assignment PIN_M11  -to fmc_la_tx_n[13]
set_location_assignment PIN_R12  -to fmc_la_tx_n[14]
set_location_assignment PIN_R13  -to fmc_la_tx_n[15]
set_location_assignment PIN_T14  -to fmc_la_tx_n[16]
set_location_assignment PIN_F9   -to fmc_la_tx_p[0]
set_location_assignment PIN_D11  -to fmc_la_tx_p[1]
set_location_assignment PIN_K12  -to fmc_la_tx_p[2]
set_location_assignment PIN_D10  -to fmc_la_tx_p[3]
set_location_assignment PIN_K8   -to fmc_la_tx_p[4]
set_location_assignment PIN_B7   -to fmc_la_tx_p[5]
set_location_assignment PIN_K10  -to fmc_la_tx_p[6]
set_location_assignment PIN_T10  -to fmc_la_tx_p[7]
set_location_assignment PIN_M12  -to fmc_la_tx_p[8]
set_location_assignment PIN_E12  -to fmc_la_tx_p[9]
set_location_assignment PIN_H12  -to fmc_la_tx_p[10]
set_location_assignment PIN_P8   -to fmc_la_tx_p[11]
set_location_assignment PIN_U12  -to fmc_la_tx_p[12]
set_location_assignment PIN_N11  -to fmc_la_tx_p[13]
set_location_assignment PIN_P12  -to fmc_la_tx_p[14]
set_location_assignment PIN_T13  -to fmc_la_tx_p[15]
set_location_assignment PIN_U14  -to fmc_la_tx_p[16]
set_location_assignment PIN_BB9  -to fmc_prsntn
set_location_assignment PIN_AN37 -to fmc_rx_led
set_location_assignment PIN_A10  -to fmc_scl
set_location_assignment PIN_B10  -to fmc_sda
set_location_assignment PIN_AY34 -to fmc_tx_led
set_location_assignment PIN_W42  -to fmc_dp_c2m_n[0]
set_location_assignment PIN_U42  -to fmc_dp_c2m_n[1]
set_location_assignment PIN_R42  -to fmc_dp_c2m_n[2]
set_location_assignment PIN_N42  -to fmc_dp_c2m_n[3]
set_location_assignment PIN_J42  -to fmc_dp_c2m_n[4]
set_location_assignment PIN_K40  -to fmc_dp_c2m_n[5]
set_location_assignment PIN_H40  -to fmc_dp_c2m_n[6]
set_location_assignment PIN_G42  -to fmc_dp_c2m_n[7]
set_location_assignment PIN_E42  -to fmc_dp_c2m_n[8]
set_location_assignment PIN_D40  -to fmc_dp_c2m_n[9]
set_location_assignment PIN_W41  -to fmc_dp_c2m_p[0]
set_location_assignment PIN_U41  -to fmc_dp_c2m_p[1]
set_location_assignment PIN_R41  -to fmc_dp_c2m_p[2]
set_location_assignment PIN_N41  -to fmc_dp_c2m_p[3]
set_location_assignment PIN_J41  -to fmc_dp_c2m_p[4]
set_location_assignment PIN_K39  -to fmc_dp_c2m_p[5]
set_location_assignment PIN_H39  -to fmc_dp_c2m_p[6]
set_location_assignment PIN_G41  -to fmc_dp_c2m_p[7]
set_location_assignment PIN_E41  -to fmc_dp_c2m_p[8]
set_location_assignment PIN_D39  -to fmc_dp_c2m_p[9]
set_location_assignment PIN_AB44 -to fmc_dp_m2c_n[0]
set_location_assignment PIN_Y44  -to fmc_dp_m2c_n[1]
set_location_assignment PIN_V44  -to fmc_dp_m2c_n[2]
set_location_assignment PIN_T44  -to fmc_dp_m2c_n[3]
set_location_assignment PIN_M44  -to fmc_dp_m2c_n[4]
set_location_assignment PIN_K44  -to fmc_dp_m2c_n[5]
set_location_assignment PIN_H44  -to fmc_dp_m2c_n[6]
set_location_assignment PIN_F44  -to fmc_dp_m2c_n[7]
set_location_assignment PIN_D44  -to fmc_dp_m2c_n[8]
set_location_assignment PIN_C42  -to fmc_dp_m2c_n[9]
set_location_assignment PIN_AB43 -to fmc_dp_m2c_p[0]
set_location_assignment PIN_Y43  -to fmc_dp_m2c_p[1]
set_location_assignment PIN_V43  -to fmc_dp_m2c_p[2]
set_location_assignment PIN_T43  -to fmc_dp_m2c_p[3]
set_location_assignment PIN_M43  -to fmc_dp_m2c_p[4]
set_location_assignment PIN_K43  -to fmc_dp_m2c_p[5]
set_location_assignment PIN_H43  -to fmc_dp_m2c_p[6]
set_location_assignment PIN_F43  -to fmc_dp_m2c_p[7]
set_location_assignment PIN_D43  -to fmc_dp_m2c_p[8]
set_location_assignment PIN_C41  -to fmc_dp_m2c_p[9]
set_location_assignment PIN_BC37 -to fpga1_cpu_resetn
set_location_assignment PIN_V26  -to fpga1_dipsw[0]
set_location_assignment PIN_V27  -to fpga1_dipsw[1]
set_location_assignment PIN_AH22 -to fpga1_dipsw[2]
set_location_assignment PIN_AP24 -to fpga1_dipsw[3]
set_location_assignment PIN_AP25 -to fpga1_dipsw[4]
set_location_assignment PIN_AH27 -to fpga1_dipsw[5]
set_location_assignment PIN_AN27 -to fpga1_dipsw[6]
set_location_assignment PIN_BC29 -to fpga1_dipsw[7]
set_location_assignment PIN_H25  -to fpga1_led_g[0]
set_location_assignment PIN_P23  -to fpga1_led_g[1]
set_location_assignment PIN_AH19 -to fpga1_led_g[2]
set_location_assignment PIN_AT11 -to fpga1_led_g[3]
set_location_assignment PIN_G23  -to fpga1_led_g[4]
set_location_assignment PIN_AY9  -to fpga1_led_g[5]
set_location_assignment PIN_H22  -to fpga1_led_g[6]
set_location_assignment PIN_BB8  -to fpga1_led_g[7]
set_location_assignment PIN_N22  -to fpga1_led_r[0]
set_location_assignment PIN_P25  -to fpga1_led_r[1]
set_location_assignment PIN_AR11 -to fpga1_led_r[2]
set_location_assignment PIN_AV13 -to fpga1_led_r[3]
set_location_assignment PIN_C22  -to fpga1_led_r[4]
set_location_assignment PIN_BA9  -to fpga1_led_r[5]
set_location_assignment PIN_N19  -to fpga1_led_r[6]
set_location_assignment PIN_BD8  -to fpga1_led_r[7]
set_location_assignment PIN_AY33 -to fpga1_pb[0]
set_location_assignment PIN_BA33 -to fpga1_pb[1]
set_location_assignment PIN_BA34 -to fpga1_pb[2]
# C2C Parallel
# for UART TX
set_location_assignment PIN_AU8  -to c2c_d[0]
# for UART RX
set_location_assignment PIN_AT8  -to c2c_d[1]
set_location_assignment PIN_AE36 -to c2c_d[2]
set_location_assignment PIN_AT9  -to c2c_d[3]
set_location_assignment PIN_AR8  -to c2c_d[4]
set_location_assignment PIN_AE35 -to c2c_d[5]
set_location_assignment PIN_AL9  -to c2c_d[6]
set_location_assignment PIN_AN11 -to c2c_d[7]
set_location_assignment PIN_AW9  -to c2c_d[8]
set_location_assignment PIN_AK9  -to c2c_d[9]
set_location_assignment PIN_AM11 -to c2c_d[10]
set_location_assignment PIN_AV8  -to c2c_d[11]
# C2C LVDS
set_location_assignment PIN_F16  -to fpga1_rx_d_n[0]
set_location_assignment PIN_AG34 -to fpga1_rx_d_n[1]
set_location_assignment PIN_G16  -to fpga1_rx_d_p[0]
set_location_assignment PIN_AF35 -to fpga1_rx_d_p[1]
set_location_assignment PIN_AJ34 -to fpga1_tx_d_n[0]
set_location_assignment PIN_AL35 -to fpga1_tx_d_n[1]
set_location_assignment PIN_AH34 -to fpga1_tx_d_p[0]
set_location_assignment PIN_AK35 -to fpga1_tx_d_p[1]
# C2C XCVR
set_location_assignment PIN_P1 -to fpga1_rx_n[0]
set_location_assignment PIN_M1 -to fpga1_rx_n[1]
set_location_assignment PIN_K1 -to fpga1_rx_n[2]
set_location_assignment PIN_H1 -to fpga1_rx_n[3]
set_location_assignment PIN_F1 -to fpga1_rx_n[4]
set_location_assignment PIN_D1 -to fpga1_rx_n[5]
set_location_assignment PIN_B1 -to fpga1_rx_n[6]
set_location_assignment PIN_C3 -to fpga1_rx_n[7]
set_location_assignment PIN_P2 -to fpga1_rx_p[0]
set_location_assignment PIN_M2 -to fpga1_rx_p[1]
set_location_assignment PIN_K2 -to fpga1_rx_p[2]
set_location_assignment PIN_H2 -to fpga1_rx_p[3]
set_location_assignment PIN_F2 -to fpga1_rx_p[4]
set_location_assignment PIN_D2 -to fpga1_rx_p[5]
set_location_assignment PIN_B2 -to fpga1_rx_p[6]
set_location_assignment PIN_C4 -to fpga1_rx_p[7]
set_location_assignment PIN_L3 -to fpga1_tx_n[0]
set_location_assignment PIN_J3 -to fpga1_tx_n[1]
set_location_assignment PIN_K5 -to fpga1_tx_n[2]
set_location_assignment PIN_H5 -to fpga1_tx_n[3]
set_location_assignment PIN_G3 -to fpga1_tx_n[4]
set_location_assignment PIN_E3 -to fpga1_tx_n[5]
set_location_assignment PIN_F5 -to fpga1_tx_n[6]
set_location_assignment PIN_D5 -to fpga1_tx_n[7]
set_location_assignment PIN_L4 -to fpga1_tx_p[0]
set_location_assignment PIN_J4 -to fpga1_tx_p[1]
set_location_assignment PIN_K6 -to fpga1_tx_p[2]
set_location_assignment PIN_H6 -to fpga1_tx_p[3]
set_location_assignment PIN_G4 -to fpga1_tx_p[4]
set_location_assignment PIN_E4 -to fpga1_tx_p[5]
set_location_assignment PIN_F6 -to fpga1_tx_p[6]
set_location_assignment PIN_D6 -to fpga1_tx_p[7]
set_location_assignment PIN_AT32 -to max5_clk
set_location_assignment PIN_AT29 -to max5_data
set_location_assignment PIN_AR33 -to plx_fatal_errn
set_location_assignment PIN_AN38 -to plx_i2c_scl0
set_location_assignment PIN_AP39 -to plx_i2c_sda0
set_location_assignment PIN_AU33 -to plx_perstn
set_location_assignment PIN_AR34 -to plx_portgoodn
set_location_assignment PIN_T25  -to pcie_led_g2
set_location_assignment PIN_BB36 -to pcie_led_g3
set_location_assignment PIN_T26  -to pcie_led_x1
set_location_assignment PIN_U26  -to pcie_led_x4
set_location_assignment PIN_U27  -to pcie_led_x8
set_location_assignment PIN_BB44 -to pcie_rx_n[0]
set_location_assignment PIN_BA42 -to pcie_rx_n[1]
set_location_assignment PIN_AW42 -to pcie_rx_n[2]
set_location_assignment PIN_AY44 -to pcie_rx_n[3]
set_location_assignment PIN_AT44 -to pcie_rx_n[4]
set_location_assignment PIN_AP44 -to pcie_rx_n[5]
set_location_assignment PIN_AM44 -to pcie_rx_n[6]
set_location_assignment PIN_AK44 -to pcie_rx_n[7]
set_location_assignment PIN_BB43 -to pcie_rx_p[0]
set_location_assignment PIN_BA41 -to pcie_rx_p[1]
set_location_assignment PIN_AW41 -to pcie_rx_p[2]
set_location_assignment PIN_AY43 -to pcie_rx_p[3]
set_location_assignment PIN_AT43 -to pcie_rx_p[4]
set_location_assignment PIN_AP43 -to pcie_rx_p[5]
set_location_assignment PIN_AM43 -to pcie_rx_p[6]
set_location_assignment PIN_AK43 -to pcie_rx_p[7]
set_location_assignment PIN_AY40 -to pcie_tx_n[0]
set_location_assignment PIN_AV40 -to pcie_tx_n[1]
set_location_assignment PIN_AT40 -to pcie_tx_n[2]
set_location_assignment PIN_AU42 -to pcie_tx_n[3]
set_location_assignment PIN_AN42 -to pcie_tx_n[4]
set_location_assignment PIN_AL42 -to pcie_tx_n[5]
set_location_assignment PIN_AJ42 -to pcie_tx_n[6]
set_location_assignment PIN_AG42 -to pcie_tx_n[7]
set_location_assignment PIN_AY39 -to pcie_tx_p[0]
set_location_assignment PIN_AV39 -to pcie_tx_p[1]
set_location_assignment PIN_AT39 -to pcie_tx_p[2]
set_location_assignment PIN_AU41 -to pcie_tx_p[3]
set_location_assignment PIN_AN41 -to pcie_tx_p[4]
set_location_assignment PIN_AL41 -to pcie_tx_p[5]
set_location_assignment PIN_AJ41 -to pcie_tx_p[6]
set_location_assignment PIN_AG41 -to pcie_tx_p[7]
set_location_assignment PIN_P35  -to rzq_5
set_location_assignment PIN_AY36 -to sva_clk_125_n
set_location_assignment PIN_AW35 -to sva_clk_125_p
set_location_assignment PIN_R25  -to sva_clk_50
set_location_assignment PIN_AR10 -to sva_clk_n
set_location_assignment PIN_AP10 -to sva_clk_p
set_location_assignment PIN_BC8  -to usb_clk
set_location_assignment PIN_BD10 -to usb_addr[0]
set_location_assignment PIN_AF13 -to usb_addr[1]
set_location_assignment PIN_AP13 -to usb_data[0]
set_location_assignment PIN_BC14 -to usb_data[1]
set_location_assignment PIN_AF17 -to usb_data[2]
set_location_assignment PIN_BD14 -to usb_data[3]
set_location_assignment PIN_AH13 -to usb_data[4]
set_location_assignment PIN_AR16 -to usb_data[5]
set_location_assignment PIN_AJ13 -to usb_data[6]
set_location_assignment PIN_BA15 -to usb_data[7]
set_location_assignment PIN_AU35 -to usb_empty
set_location_assignment PIN_AW33 -to usb_full
set_location_assignment PIN_AV34 -to usb_oen
set_location_assignment PIN_AT33 -to usb_rdn
set_location_assignment PIN_BD34 -to usb_resetn
set_location_assignment PIN_BD35 -to usb_scl
set_location_assignment PIN_BA31 -to usb_sda
set_location_assignment PIN_AJ29 -to usb_wrn
set_location_assignment PIN_AH40 -to refclka_ql0_n
set_location_assignment PIN_AH39 -to refclka_ql0_p
set_location_assignment PIN_AF39 -to refclka_ql1_n
set_location_assignment PIN_AF38 -to refclka_ql1_p
set_location_assignment PIN_Y39  -to refclka_ql2_n
set_location_assignment PIN_Y38  -to refclka_ql2_p
set_location_assignment PIN_T39  -to refclka_ql3_n
set_location_assignment PIN_T38  -to refclka_ql3_p
set_location_assignment PIN_AK6  -to refclka_qr0_n
set_location_assignment PIN_AK7  -to refclka_qr0_p
set_location_assignment PIN_Y6   -to refclka_qr2_n
set_location_assignment PIN_Y7   -to refclka_qr2_p

set_instance_assignment -name IO_STANDARD LVDS			-to clkinbota_ddr3_n
set_instance_assignment -name IO_STANDARD LVDS			-to clkinbota_ddr3_p
set_instance_assignment -name IO_STANDARD LVDS			-to clkintopa_ddr3_n
set_instance_assignment -name IO_STANDARD LVDS			-to clkintopa_ddr3_p
set_instance_assignment -name IO_STANDARD "2.5 V"		-to clock_scl
set_instance_assignment -name IO_STANDARD "2.5 V"		-to clock_sda
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3a_wen
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dm[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[32]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[33]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[34]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[35]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[36]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[37]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[38]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[39]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[40]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[41]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[42]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[43]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[44]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[45]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[46]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[47]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[48]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[49]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[50]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[51]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[52]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[53]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[54]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[55]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[56]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[57]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[58]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[59]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[60]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[61]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[62]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dq[63]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_n[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_dqs_p[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3b_wen
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3c_wen
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dm[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[32]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[33]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[34]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[35]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[36]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[37]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[38]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[39]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[40]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[41]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[42]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[43]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[44]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[45]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[46]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[47]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[48]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[49]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[50]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[51]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[52]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[53]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[54]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[55]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[56]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[57]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[58]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[59]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[60]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[61]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[62]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dq[63]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_n[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_dqs_p[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3d_wen
set_instance_assignment -name IO_STANDARD "2.5 V"		-to eeprom1_scl
set_instance_assignment -name IO_STANDARD "2.5 V"		-to eeprom1_sda
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_clk_m2c_n[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_clk_m2c_n[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_clk_m2c_p[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_clk_m2c_p[1]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fmc_ga[0]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fmc_ga[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_clk_n[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_clk_n[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_clk_p[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_clk_p[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[2]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[3]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[4]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[5]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[6]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[7]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[8]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[9]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[10]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[11]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[12]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[13]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_n[14]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[2]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[3]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[4]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[5]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[6]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[7]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[8]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[9]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[10]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[11]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[12]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[13]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_rx_p[14]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[2]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[3]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[4]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[5]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[6]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[7]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[8]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[9]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[10]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[11]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[12]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[13]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[14]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[15]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_n[16]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[0]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[1]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[2]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[3]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[4]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[5]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[6]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[7]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[8]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[9]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[10]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[11]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[12]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[13]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[14]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[15]
set_instance_assignment -name IO_STANDARD LVDS -to		fmc_la_tx_p[16]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fmc_prsntn
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fmc_rx_led
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fmc_scl
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fmc_sda
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fmc_tx_led
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga1_cpu_resetn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[2]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[3]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[4]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[5]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[6]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_dipsw[7]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_g[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_g[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_g[2]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga1_led_g[3]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_g[4]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga1_led_g[5]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_g[6]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga1_led_g[7]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_r[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_r[1]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga1_led_r[2]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_r[3]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_r[4]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga1_led_r[5]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_led_r[6]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga1_led_r[7]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_pb[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_pb[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga1_pb[2]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[0]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[1]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[2]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[3]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[4]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[5]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[6]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[7]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[8]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[9]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[10]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[11]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_rx_d_n[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_rx_d_n[1]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_rx_d_p[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_rx_d_p[1]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_tx_d_n[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_tx_d_n[1]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_tx_d_p[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga1_tx_d_p[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to max5_clk
set_instance_assignment -name IO_STANDARD "1.5 V"		-to max5_data
set_instance_assignment -name IO_STANDARD "1.5 V"		-to pcie_led_g2
set_instance_assignment -name IO_STANDARD "2.5 V"		-to pcie_led_g3
set_instance_assignment -name IO_STANDARD "1.5 V"		-to pcie_led_x1
set_instance_assignment -name IO_STANDARD "1.5 V"		-to pcie_led_x4
set_instance_assignment -name IO_STANDARD "1.5 V"		-to pcie_led_x8
set_instance_assignment -name IO_STANDARD "1.5 V"		-to plx_fatal_errn
set_instance_assignment -name IO_STANDARD "2.5 V"		-to plx_i2c_scl0
set_instance_assignment -name IO_STANDARD "2.5 V"		-to plx_i2c_sda0
set_instance_assignment -name IO_STANDARD "1.5 V"		-to plx_perstn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to plx_portgoodn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to rzq_5
set_instance_assignment -name IO_STANDARD LVDS			-to sva_clk_125_n
set_instance_assignment -name IO_STANDARD LVDS			-to sva_clk_125_p
set_instance_assignment -name IO_STANDARD "1.5 V"		-to sva_clk_50
set_instance_assignment -name IO_STANDARD LVDS			-to sva_clk_n
set_instance_assignment -name IO_STANDARD LVDS			-to sva_clk_p
set_instance_assignment -name IO_STANDARD "2.5 V"		-to usb_clk
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_addr[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_addr[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[2]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[3]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[4]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[5]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[6]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_data[7]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_empty
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_full
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_oen
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_rdn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_resetn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_scl
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_sda
set_instance_assignment -name IO_STANDARD "1.5 V"		-to usb_wrn

# Including default assignments
set_global_assignment -name REVISION_TYPE BASE -family "Stratix V"
set_global_assignment -name TIMEQUEST_MULTICORNER_ANALYSIS ON -family "Stratix V"
set_global_assignment -name TIMEQUEST_REPORT_WORST_CASE_TIMING_PATHS OFF -family "Stratix V"
set_global_assignment -name TIMEQUEST_CCPP_TRADEOFF_TOLERANCE 0 -family "Stratix V"
set_global_assignment -name TDC_CCPP_TRADEOFF_TOLERANCE 30 -family "Stratix V"
set_global_assignment -name TIMEQUEST_DO_CCPP_REMOVAL ON -family "Stratix V"
#set_global_assignment -name TIMEQUEST_SPECTRA_Q OFF -family "Stratix V"
set_global_assignment -name SYNTH_TIMING_DRIVEN_SYNTHESIS ON -family "Stratix V"
set_global_assignment -name SYNCHRONIZATION_REGISTER_CHAIN_LENGTH 3 -family "Stratix V"
set_global_assignment -name SYNTH_RESOURCE_AWARE_INFERENCE_FOR_BLOCK_RAM ON -family "Stratix V"
set_global_assignment -name STRATIXV_CONFIGURATION_SCHEME "PASSIVE SERIAL" -family "Stratix V"
set_global_assignment -name OPTIMIZE_HOLD_TIMING "ALL PATHS" -family "Stratix V"
set_global_assignment -name OPTIMIZE_MULTI_CORNER_TIMING ON -family "Stratix V"
set_global_assignment -name PROGRAMMABLE_POWER_TECHNOLOGY_SETTING AUTOMATIC -family "Stratix V"
set_global_assignment -name AUTO_DELAY_CHAINS ON -family "Stratix V"
#set_global_assignment -name ADVANCED_PHYSICAL_OPTIMIZATION ON -family "Stratix V"
set_global_assignment -name ENABLE_OCT_DONE OFF -family "Stratix V"

set_instance_assignment -name PARTITION_HIERARCHY root_partition -to | -section_id Top

