set_global_assignment -name FAMILY "Stratix V"
set_global_assignment -name DEVICE 5SGXEABN2F45C2
set_global_assignment -name ORIGINAL_QUARTUS_VERSION 11.1
set_global_assignment -name PROJECT_CREATION_TIME_DATE "19:16:12  OCTOBER 24, 2011"
set_global_assignment -name LAST_QUARTUS_VERSION "16.1.2 Standard Edition"
set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0
set_global_assignment -name MAX_CORE_JUNCTION_TEMP 85
set_global_assignment -name DEVICE_FILTER_PIN_COUNT 1932
set_global_assignment -name DEVICE_FILTER_SPEED_GRADE 2_H2
set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 256
set_global_assignment -name PARTITION_NETLIST_TYPE SOURCE -section_id Top
set_global_assignment -name PARTITION_FITTER_PRESERVATION_LEVEL PLACEMENT_AND_ROUTING -section_id Top
set_global_assignment -name PARTITION_COLOR 16764057 -section_id Top
set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "2.5 V"
set_global_assignment -name USE_CONFIGURATION_DEVICE ON
set_global_assignment -name CRC_ERROR_OPEN_DRAIN ON
set_global_assignment -name RESERVE_ALL_UNUSED_PINS_WEAK_PULLUP "AS INPUT TRI-STATED"
set_global_assignment -name OUTPUT_IO_TIMING_NEAR_END_VMEAS "HALF VCCIO" -rise
set_global_assignment -name OUTPUT_IO_TIMING_NEAR_END_VMEAS "HALF VCCIO" -fall
set_global_assignment -name OUTPUT_IO_TIMING_FAR_END_VMEAS "HALF SIGNAL SWING" -rise
set_global_assignment -name OUTPUT_IO_TIMING_FAR_END_VMEAS "HALF SIGNAL SWING" -fall
set_global_assignment -name ACTIVE_SERIAL_CLOCK FREQ_100MHZ

# 125.000MHz (NiosII)
set_location_assignment PIN_AY36	-to svb_clk_125_n
set_location_assignment PIN_AW35	-to svb_clk_125_p

# 50MHz (NiosII)
set_location_assignment PIN_R25		-to svb_clk_50

# General Purpose Clock (100MHz)
set_location_assignment PIN_AR10	-to svb_clk_n
set_location_assignment PIN_AP10	-to svb_clk_p

set_location_assignment PIN_AT32	-to max5_clk
set_location_assignment PIN_AT29	-to max5_data

# Chi-to-Chip on FPGA2 (100MHz)
set_location_assignment PIN_AH40	-to refclkb_ql0_n
set_location_assignment PIN_AH39	-to refclkb_ql0_p

# HSMC (706.250MHz)
set_location_assignment PIN_AB40	-to refclkb_ql2_n
set_location_assignment PIN_AB39	-to refclkb_ql2_p

# HSMC (100MHz)
set_location_assignment PIN_V40		-to refclkb_ql3_n
set_location_assignment PIN_V39		-to refclkb_ql3_p

# Chip-to-Chip on FPGA2 (625.000MHz)
set_location_assignment PIN_AK6		-to refclkb_qr0_n
set_location_assignment PIN_AK7		-to refclkb_qr0_p

# DDR3 top edge (100.000MHz)
set_location_assignment PIN_M25		-to clkintopb_ddr3_n
set_location_assignment PIN_N25		-to clkintopb_ddr3_p

# DDR3 bottom edge (100.000MHz)
set_location_assignment PIN_BC34	-to clkinbotb_ddr3_n
set_location_assignment PIN_BB33	-to clkinbotb_ddr3_p

set_location_assignment PIN_AR35	-to clock_scl
set_location_assignment PIN_AR36	-to clock_sda

set_location_assignment PIN_AW20	-to ddr3e_a[0]
set_location_assignment PIN_AT21	-to ddr3e_a[1]
set_location_assignment PIN_BD20	-to ddr3e_a[2]
set_location_assignment PIN_BB20	-to ddr3e_a[3]
set_location_assignment PIN_AU20	-to ddr3e_a[4]
set_location_assignment PIN_BC20	-to ddr3e_a[5]
set_location_assignment PIN_AU21	-to ddr3e_a[6]
set_location_assignment PIN_BA22	-to ddr3e_a[7]
set_location_assignment PIN_BD22	-to ddr3e_a[8]
set_location_assignment PIN_BB21	-to ddr3e_a[9]
set_location_assignment PIN_AY21	-to ddr3e_a[10]
set_location_assignment PIN_AW21	-to ddr3e_a[11]
set_location_assignment PIN_AV20	-to ddr3e_a[12]
set_location_assignment PIN_BC22	-to ddr3e_a[13]
set_location_assignment PIN_AU22	-to ddr3e_ba[0]
set_location_assignment PIN_AT20	-to ddr3e_ba[1]
set_location_assignment PIN_BA21	-to ddr3e_ba[2]
set_location_assignment PIN_AR21	-to ddr3e_casn
set_location_assignment PIN_AP21	-to ddr3e_cke
set_location_assignment PIN_AW22	-to ddr3e_clk_n
set_location_assignment PIN_AV22	-to ddr3e_clk_p
set_location_assignment PIN_AR22	-to ddr3e_csn
set_location_assignment PIN_BD23	-to ddr3e_dm[0]
set_location_assignment PIN_AM20	-to ddr3e_dm[1]
set_location_assignment PIN_AV25	-to ddr3e_dm[2]
set_location_assignment PIN_AL21	-to ddr3e_dm[3]
set_location_assignment PIN_AT24	-to ddr3e_dq[0]
set_location_assignment PIN_AU23	-to ddr3e_dq[1]
set_location_assignment PIN_AV23	-to ddr3e_dq[2]
set_location_assignment PIN_BB23	-to ddr3e_dq[3]
set_location_assignment PIN_BB24	-to ddr3e_dq[4]
set_location_assignment PIN_AY24	-to ddr3e_dq[5]
set_location_assignment PIN_BC23	-to ddr3e_dq[6]
set_location_assignment PIN_AW23	-to ddr3e_dq[7]
set_location_assignment PIN_AJ20	-to ddr3e_dq[8]
set_location_assignment PIN_AJ21	-to ddr3e_dq[9]
set_location_assignment PIN_AG19	-to ddr3e_dq[10]
set_location_assignment PIN_AN22	-to ddr3e_dq[11]
set_location_assignment PIN_AJ19	-to ddr3e_dq[12]
set_location_assignment PIN_AM22	-to ddr3e_dq[13]
set_location_assignment PIN_AG20	-to ddr3e_dq[14]
set_location_assignment PIN_AL20	-to ddr3e_dq[15]
set_location_assignment PIN_AR25	-to ddr3e_dq[16]
set_location_assignment PIN_AW24	-to ddr3e_dq[17]
set_location_assignment PIN_AU24	-to ddr3e_dq[18]
set_location_assignment PIN_AU25	-to ddr3e_dq[19]
set_location_assignment PIN_BC26	-to ddr3e_dq[20]
set_location_assignment PIN_AY25	-to ddr3e_dq[21]
set_location_assignment PIN_BA24	-to ddr3e_dq[22]
set_location_assignment PIN_BD26	-to ddr3e_dq[23]
set_location_assignment PIN_AL24	-to ddr3e_dq[24]
set_location_assignment PIN_AK23	-to ddr3e_dq[25]
set_location_assignment PIN_AN23	-to ddr3e_dq[26]
set_location_assignment PIN_AK21	-to ddr3e_dq[27]
set_location_assignment PIN_AL23	-to ddr3e_dq[28]
set_location_assignment PIN_AJ22	-to ddr3e_dq[29]
set_location_assignment PIN_AM23	-to ddr3e_dq[30]
set_location_assignment PIN_AJ23	-to ddr3e_dq[31]
set_location_assignment PIN_BD25	-to ddr3e_dqs_n[0]
set_location_assignment PIN_AH21	-to ddr3e_dqs_n[1]
set_location_assignment PIN_BB26	-to ddr3e_dqs_n[2]
set_location_assignment PIN_AT23	-to ddr3e_dqs_n[3]
set_location_assignment PIN_BC25	-to ddr3e_dqs_p[0]
set_location_assignment PIN_AG21	-to ddr3e_dqs_p[1]
set_location_assignment PIN_BA25	-to ddr3e_dqs_p[2]
set_location_assignment PIN_AR23	-to ddr3e_dqs_p[3]
set_location_assignment PIN_AK20	-to ddr3e_odt
set_location_assignment PIN_AR20	-to ddr3e_rasn
set_location_assignment PIN_AR24	-to ddr3e_resetn
set_location_assignment PIN_AY22	-to ddr3e_wen
set_location_assignment PIN_AP31	-to ddr3f_a[0]
set_location_assignment PIN_AR31	-to ddr3f_a[1]
set_location_assignment PIN_AN31	-to ddr3f_a[10]
set_location_assignment PIN_AK32	-to ddr3f_a[11]
set_location_assignment PIN_AR32	-to ddr3f_a[12]
set_location_assignment PIN_AJ32	-to ddr3f_a[13]
set_location_assignment PIN_AM31	-to ddr3f_a[2]
set_location_assignment PIN_AE34	-to ddr3f_a[3]
set_location_assignment PIN_AF32	-to ddr3f_a[4]
set_location_assignment PIN_AD33	-to ddr3f_a[5]
set_location_assignment PIN_AF31	-to ddr3f_a[6]
set_location_assignment PIN_AG32	-to ddr3f_a[7]
set_location_assignment PIN_AE29	-to ddr3f_a[8]
set_location_assignment PIN_AJ33	-to ddr3f_a[9]
set_location_assignment PIN_AE33	-to ddr3f_ba[0]
set_location_assignment PIN_AH33	-to ddr3f_ba[1]
set_location_assignment PIN_AM32	-to ddr3f_ba[2]
set_location_assignment PIN_AK33	-to ddr3f_casn
set_location_assignment PIN_AE31	-to ddr3f_cke
set_location_assignment PIN_AE32	-to ddr3f_clk_n
set_location_assignment PIN_AD32	-to ddr3f_clk_p
set_location_assignment PIN_AG33	-to ddr3f_csn
set_location_assignment PIN_BA30	-to ddr3f_dm[0]
set_location_assignment PIN_AG25	-to ddr3f_dm[1]
set_location_assignment PIN_AN30	-to ddr3f_dm[2]
set_location_assignment PIN_AJ28	-to ddr3f_dm[3]
set_location_assignment PIN_AP27	-to ddr3f_dm[4]
set_location_assignment PIN_AR29	-to ddr3f_dm[5]
set_location_assignment PIN_AT27	-to ddr3f_dm[6]
set_location_assignment PIN_BA28	-to ddr3f_dm[7]
set_location_assignment PIN_AY31	-to ddr3f_dq[0]
set_location_assignment PIN_BC32	-to ddr3f_dq[1]
set_location_assignment PIN_BB32	-to ddr3f_dq[2]
set_location_assignment PIN_AW30	-to ddr3f_dq[3]
set_location_assignment PIN_BD32	-to ddr3f_dq[4]
set_location_assignment PIN_BD31	-to ddr3f_dq[5]
set_location_assignment PIN_BB30	-to ddr3f_dq[6]
set_location_assignment PIN_BC31	-to ddr3f_dq[7]
set_location_assignment PIN_AF29	-to ddr3f_dq[8]
set_location_assignment PIN_AF28	-to ddr3f_dq[9]
set_location_assignment PIN_AG29	-to ddr3f_dq[10]
set_location_assignment PIN_AG26	-to ddr3f_dq[11]
set_location_assignment PIN_AG30	-to ddr3f_dq[12]
set_location_assignment PIN_AG27	-to ddr3f_dq[13]
set_location_assignment PIN_AK29	-to ddr3f_dq[14]
set_location_assignment PIN_AG28	-to ddr3f_dq[15]
set_location_assignment PIN_AT30	-to ddr3f_dq[16]
set_location_assignment PIN_AR30	-to ddr3f_dq[17]
set_location_assignment PIN_AP30	-to ddr3f_dq[18]
set_location_assignment PIN_AU32	-to ddr3f_dq[19]
set_location_assignment PIN_AJ31	-to ddr3f_dq[20]
set_location_assignment PIN_AH30	-to ddr3f_dq[21]
set_location_assignment PIN_AJ30	-to ddr3f_dq[22]
set_location_assignment PIN_AH31	-to ddr3f_dq[23]
set_location_assignment PIN_AK26	-to ddr3f_dq[24]
set_location_assignment PIN_AH24	-to ddr3f_dq[25]
set_location_assignment PIN_AK24	-to ddr3f_dq[26]
set_location_assignment PIN_AH25	-to ddr3f_dq[27]
set_location_assignment PIN_AL26	-to ddr3f_dq[28]
set_location_assignment PIN_AH28	-to ddr3f_dq[29]
set_location_assignment PIN_AJ24	-to ddr3f_dq[30]
set_location_assignment PIN_AJ27	-to ddr3f_dq[31]
set_location_assignment PIN_AV29	-to ddr3f_dq[32]
set_location_assignment PIN_AM28	-to ddr3f_dq[33]
set_location_assignment PIN_AV28	-to ddr3f_dq[34]
set_location_assignment PIN_AL27	-to ddr3f_dq[35]
set_location_assignment PIN_AU29	-to ddr3f_dq[36]
set_location_assignment PIN_AK27	-to ddr3f_dq[37]
set_location_assignment PIN_AU28	-to ddr3f_dq[38]
set_location_assignment PIN_AL28	-to ddr3f_dq[39]
set_location_assignment PIN_AW32	-to ddr3f_dq[40]
set_location_assignment PIN_AU30	-to ddr3f_dq[41]
set_location_assignment PIN_AV32	-to ddr3f_dq[42]
set_location_assignment PIN_AP28	-to ddr3f_dq[43]
set_location_assignment PIN_AM29	-to ddr3f_dq[44]
set_location_assignment PIN_AN28	-to ddr3f_dq[45]
set_location_assignment PIN_AU31	-to ddr3f_dq[46]
set_location_assignment PIN_AV31	-to ddr3f_dq[47]
set_location_assignment PIN_AN25	-to ddr3f_dq[48]
set_location_assignment PIN_AU27	-to ddr3f_dq[49]
set_location_assignment PIN_AM26	-to ddr3f_dq[50]
set_location_assignment PIN_AW26	-to ddr3f_dq[51]
set_location_assignment PIN_AV26	-to ddr3f_dq[52]
set_location_assignment PIN_AM25	-to ddr3f_dq[53]
set_location_assignment PIN_AL25	-to ddr3f_dq[54]
set_location_assignment PIN_AR26	-to ddr3f_dq[55]
set_location_assignment PIN_AW27	-to ddr3f_dq[56]
set_location_assignment PIN_BD29	-to ddr3f_dq[57]
set_location_assignment PIN_AY27	-to ddr3f_dq[58]
set_location_assignment PIN_AY28	-to ddr3f_dq[59]
set_location_assignment PIN_BA27	-to ddr3f_dq[60]
set_location_assignment PIN_AW29	-to ddr3f_dq[61]
set_location_assignment PIN_BB27	-to ddr3f_dq[62]
set_location_assignment PIN_BB29	-to ddr3f_dq[63]
set_location_assignment PIN_BA29	-to ddr3f_dqs_n[0]
set_location_assignment PIN_AE28	-to ddr3f_dqs_n[1]
set_location_assignment PIN_AL31	-to ddr3f_dqs_n[2]
set_location_assignment PIN_AJ26	-to ddr3f_dqs_n[3]
set_location_assignment PIN_AR28	-to ddr3f_dqs_n[4]
set_location_assignment PIN_AL29	-to ddr3f_dqs_n[5]
set_location_assignment PIN_AU26	-to ddr3f_dqs_n[6]
set_location_assignment PIN_BD28	-to ddr3f_dqs_n[7]
set_location_assignment PIN_AY30	-to ddr3f_dqs_p[0]
set_location_assignment PIN_AE27	-to ddr3f_dqs_p[1]
set_location_assignment PIN_AL30	-to ddr3f_dqs_p[2]
set_location_assignment PIN_AJ25	-to ddr3f_dqs_p[3]
set_location_assignment PIN_AR27	-to ddr3f_dqs_p[4]
set_location_assignment PIN_AK30	-to ddr3f_dqs_p[5]
set_location_assignment PIN_AT26	-to ddr3f_dqs_p[6]
set_location_assignment PIN_BC28	-to ddr3f_dqs_p[7]
set_location_assignment PIN_AF34	-to ddr3f_odt
set_location_assignment PIN_AN33	-to ddr3f_rasn
set_location_assignment PIN_AE30	-to ddr3f_resetn
set_location_assignment PIN_AP33	-to ddr3f_wen
set_location_assignment PIN_G28		-to ddr3g_a[0]
set_location_assignment PIN_G26		-to ddr3g_a[1]
set_location_assignment PIN_F26		-to ddr3g_a[2]
set_location_assignment PIN_D29		-to ddr3g_a[3]
set_location_assignment PIN_A26		-to ddr3g_a[4]
set_location_assignment PIN_C27		-to ddr3g_a[5]
set_location_assignment PIN_C28		-to ddr3g_a[6]
set_location_assignment PIN_B28		-to ddr3g_a[7]
set_location_assignment PIN_A28		-to ddr3g_a[8]
set_location_assignment PIN_E27		-to ddr3g_a[9]
set_location_assignment PIN_H27		-to ddr3g_a[10]
set_location_assignment PIN_F28		-to ddr3g_a[11]
set_location_assignment PIN_H28		-to ddr3g_a[12]
set_location_assignment PIN_D27		-to ddr3g_a[13]
set_location_assignment PIN_F29		-to ddr3g_ba[0]
set_location_assignment PIN_B26		-to ddr3g_ba[1]
set_location_assignment PIN_T27		-to ddr3g_ba[2]
set_location_assignment PIN_K28		-to ddr3g_casn
set_location_assignment PIN_G29		-to ddr3g_cke
set_location_assignment PIN_H26		-to ddr3g_clk_n
set_location_assignment PIN_J27		-to ddr3g_clk_p
set_location_assignment PIN_E29		-to ddr3g_csn
set_location_assignment PIN_P27		-to ddr3g_dm[0]
set_location_assignment PIN_E24		-to ddr3g_dm[1]
set_location_assignment PIN_K24		-to ddr3g_dm[2]
set_location_assignment PIN_F25		-to ddr3g_dm[3]
set_location_assignment PIN_L26		-to ddr3g_dq[0]
set_location_assignment PIN_M27		-to ddr3g_dq[1]
set_location_assignment PIN_N26		-to ddr3g_dq[2]
set_location_assignment PIN_M28		-to ddr3g_dq[3]
set_location_assignment PIN_N28		-to ddr3g_dq[4]
set_location_assignment PIN_P29		-to ddr3g_dq[5]
set_location_assignment PIN_R27		-to ddr3g_dq[6]
set_location_assignment PIN_P28		-to ddr3g_dq[7]
set_location_assignment PIN_B23		-to ddr3g_dq[8]
set_location_assignment PIN_D24		-to ddr3g_dq[9]
set_location_assignment PIN_A23		-to ddr3g_dq[10]
set_location_assignment PIN_E23		-to ddr3g_dq[11]
set_location_assignment PIN_B25		-to ddr3g_dq[12]
set_location_assignment PIN_F23		-to ddr3g_dq[13]
set_location_assignment PIN_A25		-to ddr3g_dq[14]
set_location_assignment PIN_D23		-to ddr3g_dq[15]
set_location_assignment PIN_M23		-to ddr3g_dq[16]
set_location_assignment PIN_N23		-to ddr3g_dq[17]
set_location_assignment PIN_L24		-to ddr3g_dq[18]
set_location_assignment PIN_L23		-to ddr3g_dq[19]
set_location_assignment PIN_T24		-to ddr3g_dq[20]
set_location_assignment PIN_U24		-to ddr3g_dq[21]
set_location_assignment PIN_T23		-to ddr3g_dq[22]
set_location_assignment PIN_U23		-to ddr3g_dq[23]
set_location_assignment PIN_J25		-to ddr3g_dq[24]
set_location_assignment PIN_F24		-to ddr3g_dq[25]
set_location_assignment PIN_H24		-to ddr3g_dq[26]
set_location_assignment PIN_D26		-to ddr3g_dq[27]
set_location_assignment PIN_J24		-to ddr3g_dq[28]
set_location_assignment PIN_E26		-to ddr3g_dq[29]
set_location_assignment PIN_H23		-to ddr3g_dq[30]
set_location_assignment PIN_G25		-to ddr3g_dq[31]
set_location_assignment PIN_K27		-to ddr3g_dqs_n[0]
set_location_assignment PIN_C24		-to ddr3g_dqs_n[1]
set_location_assignment PIN_P24		-to ddr3g_dqs_n[2]
set_location_assignment PIN_K25		-to ddr3g_dqs_n[3]
set_location_assignment PIN_L27		-to ddr3g_dqs_p[0]
set_location_assignment PIN_C25		-to ddr3g_dqs_p[1]
set_location_assignment PIN_R24		-to ddr3g_dqs_p[2]
set_location_assignment PIN_K26		-to ddr3g_dqs_p[3]
set_location_assignment PIN_H29		-to ddr3g_odt
set_location_assignment PIN_J28		-to ddr3g_rasn
set_location_assignment PIN_A29		-to ddr3g_resetn
set_location_assignment PIN_P26		-to ddr3g_wen
set_location_assignment PIN_E18		-to ddr3h_a[0]
set_location_assignment PIN_E17		-to ddr3h_a[1]
set_location_assignment PIN_H17		-to ddr3h_a[2]
set_location_assignment PIN_M18		-to ddr3h_a[3]
set_location_assignment PIN_C18		-to ddr3h_a[4]
set_location_assignment PIN_P17		-to ddr3h_a[5]
set_location_assignment PIN_A17		-to ddr3h_a[6]
set_location_assignment PIN_R18		-to ddr3h_a[7]
set_location_assignment PIN_A19		-to ddr3h_a[8]
set_location_assignment PIN_B17		-to ddr3h_a[9]
set_location_assignment PIN_H19		-to ddr3h_a[10]
set_location_assignment PIN_D18		-to ddr3h_a[11]
set_location_assignment PIN_G17		-to ddr3h_a[12]
set_location_assignment PIN_B19		-to ddr3h_a[13]
set_location_assignment PIN_M17		-to ddr3h_ba[0]
set_location_assignment PIN_N17		-to ddr3h_ba[1]
set_location_assignment PIN_F17		-to ddr3h_ba[2]
set_location_assignment PIN_K17		-to ddr3h_casn
set_location_assignment PIN_K18		-to ddr3h_cke
set_location_assignment PIN_P18		-to ddr3h_clk_n
set_location_assignment PIN_P19		-to ddr3h_clk_p
set_location_assignment PIN_L17		-to ddr3h_csn
set_location_assignment PIN_E21		-to ddr3h_dm[0]
set_location_assignment PIN_K22		-to ddr3h_dm[1]
set_location_assignment PIN_R21		-to ddr3h_dm[2]
set_location_assignment PIN_T18		-to ddr3h_dm[3]
set_location_assignment PIN_H13		-to ddr3h_dm[4]
set_location_assignment PIN_M15		-to ddr3h_dm[5]
set_location_assignment PIN_U15		-to ddr3h_dm[6]
set_location_assignment PIN_A14		-to ddr3h_dm[7]
set_location_assignment PIN_E20		-to ddr3h_dq[0]
set_location_assignment PIN_B20		-to ddr3h_dq[1]
set_location_assignment PIN_F22		-to ddr3h_dq[2]
set_location_assignment PIN_F21		-to ddr3h_dq[3]
set_location_assignment PIN_A22		-to ddr3h_dq[4]
set_location_assignment PIN_A20		-to ddr3h_dq[5]
set_location_assignment PIN_B22		-to ddr3h_dq[6]
set_location_assignment PIN_C21		-to ddr3h_dq[7]
set_location_assignment PIN_G22		-to ddr3h_dq[8]
set_location_assignment PIN_J21		-to ddr3h_dq[9]
set_location_assignment PIN_F20		-to ddr3h_dq[10]
set_location_assignment PIN_K21		-to ddr3h_dq[11]
set_location_assignment PIN_J22		-to ddr3h_dq[12]
set_location_assignment PIN_L21		-to ddr3h_dq[13]
set_location_assignment PIN_G20		-to ddr3h_dq[14]
set_location_assignment PIN_K20		-to ddr3h_dq[15]
set_location_assignment PIN_R22		-to ddr3h_dq[16]
set_location_assignment PIN_P21		-to ddr3h_dq[17]
set_location_assignment PIN_T22		-to ddr3h_dq[18]
set_location_assignment PIN_M22		-to ddr3h_dq[19]
set_location_assignment PIN_U20		-to ddr3h_dq[20]
set_location_assignment PIN_V19		-to ddr3h_dq[21]
set_location_assignment PIN_T21		-to ddr3h_dq[22]
set_location_assignment PIN_U21		-to ddr3h_dq[23]
set_location_assignment PIN_P20		-to ddr3h_dq[24]
set_location_assignment PIN_L20		-to ddr3h_dq[25]
set_location_assignment PIN_K19		-to ddr3h_dq[26]
set_location_assignment PIN_U18		-to ddr3h_dq[27]
set_location_assignment PIN_N20		-to ddr3h_dq[28]
set_location_assignment PIN_W18		-to ddr3h_dq[29]
set_location_assignment PIN_M20		-to ddr3h_dq[30]
set_location_assignment PIN_V18		-to ddr3h_dq[31]
set_location_assignment PIN_K13		-to ddr3h_dq[32]
set_location_assignment PIN_G14		-to ddr3h_dq[33]
set_location_assignment PIN_J13		-to ddr3h_dq[34]
set_location_assignment PIN_H14		-to ddr3h_dq[35]
set_location_assignment PIN_F13		-to ddr3h_dq[36]
set_location_assignment PIN_K16		-to ddr3h_dq[37]
set_location_assignment PIN_G13		-to ddr3h_dq[38]
set_location_assignment PIN_J16		-to ddr3h_dq[39]
set_location_assignment PIN_P16		-to ddr3h_dq[40]
set_location_assignment PIN_N16		-to ddr3h_dq[41]
set_location_assignment PIN_R16		-to ddr3h_dq[42]
set_location_assignment PIN_J15		-to ddr3h_dq[43]
set_location_assignment PIN_T16		-to ddr3h_dq[44]
set_location_assignment PIN_L14		-to ddr3h_dq[45]
set_location_assignment PIN_T17		-to ddr3h_dq[46]
set_location_assignment PIN_M14		-to ddr3h_dq[47]
set_location_assignment PIN_P15		-to ddr3h_dq[48]
set_location_assignment PIN_W17		-to ddr3h_dq[49]
set_location_assignment PIN_T15		-to ddr3h_dq[50]
set_location_assignment PIN_V16		-to ddr3h_dq[51]
set_location_assignment PIN_W14		-to ddr3h_dq[52]
set_location_assignment PIN_V13		-to ddr3h_dq[53]
set_location_assignment PIN_V15		-to ddr3h_dq[54]
set_location_assignment PIN_Y17		-to ddr3h_dq[55]
set_location_assignment PIN_C15		-to ddr3h_dq[56]
set_location_assignment PIN_A13		-to ddr3h_dq[57]
set_location_assignment PIN_D14		-to ddr3h_dq[58]
set_location_assignment PIN_B14		-to ddr3h_dq[59]
set_location_assignment PIN_F14		-to ddr3h_dq[60]
set_location_assignment PIN_B13		-to ddr3h_dq[61]
set_location_assignment PIN_E14		-to ddr3h_dq[62]
set_location_assignment PIN_C13		-to ddr3h_dq[63]
set_location_assignment PIN_D20		-to ddr3h_dqs_n[0]
set_location_assignment PIN_H20		-to ddr3h_dqs_n[1]
set_location_assignment PIN_V20		-to ddr3h_dqs_n[2]
set_location_assignment PIN_T19		-to ddr3h_dqs_n[3]
set_location_assignment PIN_K14		-to ddr3h_dqs_n[4]
set_location_assignment PIN_U17		-to ddr3h_dqs_n[5]
set_location_assignment PIN_W16		-to ddr3h_dqs_n[6]
set_location_assignment PIN_D15		-to ddr3h_dqs_n[7]
set_location_assignment PIN_D21		-to ddr3h_dqs_p[0]
set_location_assignment PIN_H21		-to ddr3h_dqs_p[1]
set_location_assignment PIN_V21		-to ddr3h_dqs_p[2]
set_location_assignment PIN_T20		-to ddr3h_dqs_p[3]
set_location_assignment PIN_L15		-to ddr3h_dqs_p[4]
set_location_assignment PIN_V17		-to ddr3h_dqs_p[5]
set_location_assignment PIN_Y16		-to ddr3h_dqs_p[6]
set_location_assignment PIN_E15		-to ddr3h_dqs_p[7]
set_location_assignment PIN_L18		-to ddr3h_odt
set_location_assignment PIN_J19		-to ddr3h_rasn
set_location_assignment PIN_R19		-to ddr3h_resetn
set_location_assignment PIN_H16		-to ddr3h_wen
set_location_assignment PIN_AR9		-to eeprom2_scl
set_location_assignment PIN_AP9		-to eeprom2_sda
# C2C Parallel
# connect to hsmc_d[2], for FPGA1 UART TX
set_location_assignment PIN_AL9		-to c2c_d[0]
# connect to hsmc_d[3], for FPGA1 UART RX
set_location_assignment PIN_AN11	-to c2c_d[1]
set_location_assignment PIN_BA36	-to c2c_d[2]
set_location_assignment PIN_AK9		-to c2c_d[3]
set_location_assignment PIN_AM11	-to c2c_d[4]
set_location_assignment PIN_AY37	-to c2c_d[5]
set_location_assignment PIN_AU8		-to c2c_d[6]
set_location_assignment PIN_AT8		-to c2c_d[7]
set_location_assignment PIN_AJ34	-to c2c_d[8]
set_location_assignment PIN_AT9		-to c2c_d[9]
set_location_assignment PIN_AR8		-to c2c_d[10]
set_location_assignment PIN_AH34	-to c2c_d[11]
# C2C LVDS
set_location_assignment PIN_AW9		-to fpga2_rx_d_n[0]
set_location_assignment PIN_AL35	-to fpga2_rx_d_n[1]
set_location_assignment PIN_AV8		-to fpga2_rx_d_p[0]
set_location_assignment PIN_AK35	-to fpga2_rx_d_p[1]
set_location_assignment PIN_BA9		-to fpga2_tx_d_n[0]
set_location_assignment PIN_AG34	-to fpga2_tx_d_n[1]
set_location_assignment PIN_AY9		-to fpga2_tx_d_p[0]
set_location_assignment PIN_AF35	-to fpga2_tx_d_p[1]
# C2C XCVR
set_location_assignment PIN_BB1		-to fpga2_rx_n[0]
set_location_assignment PIN_BA3		-to fpga2_rx_n[1]
set_location_assignment PIN_AW3		-to fpga2_rx_n[2]
set_location_assignment PIN_AY1		-to fpga2_rx_n[3]
set_location_assignment PIN_AV1		-to fpga2_rx_n[4]
set_location_assignment PIN_AT1		-to fpga2_rx_n[5]
set_location_assignment PIN_AP1		-to fpga2_rx_n[6]
set_location_assignment PIN_AM1		-to fpga2_rx_n[7]
set_location_assignment PIN_BB2		-to fpga2_rx_p[0]
set_location_assignment PIN_BA4		-to fpga2_rx_p[1]
set_location_assignment PIN_AW4		-to fpga2_rx_p[2]
set_location_assignment PIN_AY2		-to fpga2_rx_p[3]
set_location_assignment PIN_AV2		-to fpga2_rx_p[4]
set_location_assignment PIN_AT2		-to fpga2_rx_p[5]
set_location_assignment PIN_AP2		-to fpga2_rx_p[6]
set_location_assignment PIN_AM2		-to fpga2_rx_p[7]
set_location_assignment PIN_AY5		-to fpga2_tx_n[0]
set_location_assignment PIN_AV5		-to fpga2_tx_n[1]
set_location_assignment PIN_AT5		-to fpga2_tx_n[2]
set_location_assignment PIN_AU3		-to fpga2_tx_n[3]
set_location_assignment PIN_AR3		-to fpga2_tx_n[4]
set_location_assignment PIN_AN3		-to fpga2_tx_n[5]
set_location_assignment PIN_AL3		-to fpga2_tx_n[6]
set_location_assignment PIN_AJ3		-to fpga2_tx_n[7]
set_location_assignment PIN_AY6		-to fpga2_tx_p[0]
set_location_assignment PIN_AV6		-to fpga2_tx_p[1]
set_location_assignment PIN_AT6		-to fpga2_tx_p[2]
set_location_assignment PIN_AU4		-to fpga2_tx_p[3]
set_location_assignment PIN_AR4		-to fpga2_tx_p[4]
set_location_assignment PIN_AN4		-to fpga2_tx_p[5]
set_location_assignment PIN_AL4		-to fpga2_tx_p[6]
set_location_assignment PIN_AJ4		-to fpga2_tx_p[7]
set_location_assignment PIN_H18		-to hsmc_clk_in_n1
set_location_assignment PIN_L9		-to hsmc_clk_in_n2
set_location_assignment PIN_J18		-to hsmc_clk_in_p1
set_location_assignment PIN_M9		-to hsmc_clk_in_p2
set_location_assignment PIN_BC8		-to hsmc_clk_in0
set_location_assignment PIN_BD7		-to hsmc_clk_out_n1
set_location_assignment PIN_A10		-to hsmc_clk_out_n2
set_location_assignment PIN_BC7		-to hsmc_clk_out_p1
set_location_assignment PIN_B10		-to hsmc_clk_out_p2
set_location_assignment PIN_AR11	-to hsmc_clk_out0
set_location_assignment PIN_AH13	-to hsmc_prsntn
set_location_assignment PIN_BD10	-to hsmc_tx_led
set_location_assignment PIN_BD14	-to hsmc_rx_led
set_location_assignment PIN_BB36	-to hsmc_scl
set_location_assignment PIN_BB8		-to hsmc_sda
# UART TX, connect to PIN3 of HSMC Debug Board, for FPGA2 UART TX
set_location_assignment PIN_BB9		-to hsmc_d[0]
# UART RX, connect to PIN4 of HSMC Debug Board, for FPGA2 UART RX
set_location_assignment PIN_AN37	-to hsmc_d[1]
# UART TX, connect to PIN5 of HSMC Debug Board, for FPGA1 UART TX
set_location_assignment PIN_AT11	-to hsmc_d[2]
# UART RX, connect to PIN6 of HSMC Debug Board, for FPGA1 UART RX
set_location_assignment PIN_BD8		-to hsmc_d[3]
set_location_assignment PIN_V11		-to hsmc_rx_d_n[0]
set_location_assignment PIN_V9		-to hsmc_rx_d_n[1]
set_location_assignment PIN_T9		-to hsmc_rx_d_n[2]
set_location_assignment PIN_T11		-to hsmc_rx_d_n[3]
set_location_assignment PIN_N14		-to hsmc_rx_d_n[4]
set_location_assignment PIN_N13		-to hsmc_rx_d_n[5]
set_location_assignment PIN_L11		-to hsmc_rx_d_n[6]
set_location_assignment PIN_L8		-to hsmc_rx_d_n[7]
set_location_assignment PIN_H10		-to hsmc_rx_d_n[8]
set_location_assignment PIN_H8		-to hsmc_rx_d_n[9]
set_location_assignment PIN_F11		-to hsmc_rx_d_n[10]
set_location_assignment PIN_F8		-to hsmc_rx_d_n[11]
set_location_assignment PIN_F10		-to hsmc_rx_d_n[12]
set_location_assignment PIN_D9		-to hsmc_rx_d_n[13]
set_location_assignment PIN_C12		-to hsmc_rx_d_n[14]
set_location_assignment PIN_A11		-to hsmc_rx_d_n[15]
set_location_assignment PIN_A8		-to hsmc_rx_d_n[16]
set_location_assignment PIN_V12		-to hsmc_rx_d_p[0]
set_location_assignment PIN_V10		-to hsmc_rx_d_p[1]
set_location_assignment PIN_U9		-to hsmc_rx_d_p[2]
set_location_assignment PIN_T12		-to hsmc_rx_d_p[3]
set_location_assignment PIN_P14		-to hsmc_rx_d_p[4]
set_location_assignment PIN_P13		-to hsmc_rx_d_p[5]
set_location_assignment PIN_K11		-to hsmc_rx_d_p[6]
set_location_assignment PIN_M8		-to hsmc_rx_d_p[7]
set_location_assignment PIN_J10		-to hsmc_rx_d_p[8]
set_location_assignment PIN_H9		-to hsmc_rx_d_p[9]
set_location_assignment PIN_G11		-to hsmc_rx_d_p[10]
set_location_assignment PIN_G8		-to hsmc_rx_d_p[11]
set_location_assignment PIN_G10		-to hsmc_rx_d_p[12]
set_location_assignment PIN_E8		-to hsmc_rx_d_p[13]
set_location_assignment PIN_D12		-to hsmc_rx_d_p[14]
set_location_assignment PIN_B11		-to hsmc_rx_d_p[15]
set_location_assignment PIN_B8		-to hsmc_rx_d_p[16]
set_location_assignment PIN_T14		-to hsmc_tx_d_n[0]
set_location_assignment PIN_U11		-to hsmc_tx_d_n[1]
set_location_assignment PIN_R13		-to hsmc_tx_d_n[2]
set_location_assignment PIN_R10		-to hsmc_tx_d_n[3]
set_location_assignment PIN_R12		-to hsmc_tx_d_n[4]
set_location_assignment PIN_N8		-to hsmc_tx_d_n[5]
set_location_assignment PIN_M11		-to hsmc_tx_d_n[6]
set_location_assignment PIN_L12		-to hsmc_tx_d_n[7]
set_location_assignment PIN_J12		-to hsmc_tx_d_n[8]
set_location_assignment PIN_J9		-to hsmc_tx_d_n[9]
set_location_assignment PIN_K9		-to hsmc_tx_d_n[10]
set_location_assignment PIN_H11		-to hsmc_tx_d_n[11]
set_location_assignment PIN_E11		-to hsmc_tx_d_n[12]
set_location_assignment PIN_E9		-to hsmc_tx_d_n[13]
set_location_assignment PIN_C9		-to hsmc_tx_d_n[14]
set_location_assignment PIN_C10		-to hsmc_tx_d_n[15]
set_location_assignment PIN_A7		-to hsmc_tx_d_n[16]
set_location_assignment PIN_U14		-to hsmc_tx_d_p[0]
set_location_assignment PIN_U12		-to hsmc_tx_d_p[1]
set_location_assignment PIN_T13		-to hsmc_tx_d_p[2]
set_location_assignment PIN_T10		-to hsmc_tx_d_p[3]
set_location_assignment PIN_P12		-to hsmc_tx_d_p[4]
set_location_assignment PIN_P8		-to hsmc_tx_d_p[5]
set_location_assignment PIN_N11		-to hsmc_tx_d_p[6]
set_location_assignment PIN_M12		-to hsmc_tx_d_p[7]
set_location_assignment PIN_K12		-to hsmc_tx_d_p[8]
set_location_assignment PIN_K8		-to hsmc_tx_d_p[9]
set_location_assignment PIN_K10		-to hsmc_tx_d_p[10]
set_location_assignment PIN_H12		-to hsmc_tx_d_p[11]
set_location_assignment PIN_E12		-to hsmc_tx_d_p[12]
set_location_assignment PIN_F9		-to hsmc_tx_d_p[13]
set_location_assignment PIN_D10		-to hsmc_tx_d_p[14]
set_location_assignment PIN_D11		-to hsmc_tx_d_p[15]
set_location_assignment PIN_B7		-to hsmc_tx_d_p[16]
set_location_assignment PIN_AB44	-to hsmc_rx_n[0]
set_location_assignment PIN_Y44		-to hsmc_rx_n[1]
set_location_assignment PIN_V44		-to hsmc_rx_n[2]
set_location_assignment PIN_T44		-to hsmc_rx_n[3]
set_location_assignment PIN_M44		-to hsmc_rx_n[4]
set_location_assignment PIN_K44		-to hsmc_rx_n[5]
set_location_assignment PIN_H44		-to hsmc_rx_n[6]
set_location_assignment PIN_F44		-to hsmc_rx_n[7]
set_location_assignment PIN_AB43	-to hsmc_rx_p[0]
set_location_assignment PIN_Y43		-to hsmc_rx_p[1]
set_location_assignment PIN_V43		-to hsmc_rx_p[2]
set_location_assignment PIN_T43		-to hsmc_rx_p[3]
set_location_assignment PIN_M43		-to hsmc_rx_p[4]
set_location_assignment PIN_K43		-to hsmc_rx_p[5]
set_location_assignment PIN_H43		-to hsmc_rx_p[6]
set_location_assignment PIN_F43		-to hsmc_rx_p[7]
set_location_assignment PIN_W42		-to hsmc_tx_n[0]
set_location_assignment PIN_U42		-to hsmc_tx_n[1]
set_location_assignment PIN_R42		-to hsmc_tx_n[2]
set_location_assignment PIN_N42		-to hsmc_tx_n[3]
set_location_assignment PIN_J42		-to hsmc_tx_n[4]
set_location_assignment PIN_K40		-to hsmc_tx_n[5]
set_location_assignment PIN_H40		-to hsmc_tx_n[6]
set_location_assignment PIN_G42		-to hsmc_tx_n[7]
set_location_assignment PIN_W41		-to hsmc_tx_p[0]
set_location_assignment PIN_U41		-to hsmc_tx_p[1]
set_location_assignment PIN_R41		-to hsmc_tx_p[2]
set_location_assignment PIN_N41		-to hsmc_tx_p[3]
set_location_assignment PIN_J41		-to hsmc_tx_p[4]
set_location_assignment PIN_K39		-to hsmc_tx_p[5]
set_location_assignment PIN_H39		-to hsmc_tx_p[6]
set_location_assignment PIN_G41		-to hsmc_tx_p[7]
set_location_assignment PIN_BC29	-to pcie_led_x16
set_location_assignment PIN_BB44	-to pcie_rx_n[8]
set_location_assignment PIN_BA42	-to pcie_rx_n[9]
set_location_assignment PIN_AW42	-to pcie_rx_n[10]
set_location_assignment PIN_AY44	-to pcie_rx_n[11]
set_location_assignment PIN_AT44	-to pcie_rx_n[12]
set_location_assignment PIN_AP44	-to pcie_rx_n[13]
set_location_assignment PIN_AM44	-to pcie_rx_n[14]
set_location_assignment PIN_AK44	-to pcie_rx_n[15]
set_location_assignment PIN_BB43	-to pcie_rx_p[8]
set_location_assignment PIN_BA41	-to pcie_rx_p[9]
set_location_assignment PIN_AW41	-to pcie_rx_p[10]
set_location_assignment PIN_AY43	-to pcie_rx_p[11]
set_location_assignment PIN_AT43	-to pcie_rx_p[12]
set_location_assignment PIN_AP43	-to pcie_rx_p[13]
set_location_assignment PIN_AM43	-to pcie_rx_p[14]
set_location_assignment PIN_AK43	-to pcie_rx_p[15]
set_location_assignment PIN_AY40	-to pcie_tx_n[8]
set_location_assignment PIN_AV40	-to pcie_tx_n[9]
set_location_assignment PIN_AT40	-to pcie_tx_n[10]
set_location_assignment PIN_AU42	-to pcie_tx_n[11]
set_location_assignment PIN_AN42	-to pcie_tx_n[12]
set_location_assignment PIN_AL42	-to pcie_tx_n[13]
set_location_assignment PIN_AJ42	-to pcie_tx_n[14]
set_location_assignment PIN_AG42	-to pcie_tx_n[15]
set_location_assignment PIN_AY39	-to pcie_tx_p[8]
set_location_assignment PIN_AV39	-to pcie_tx_p[9]
set_location_assignment PIN_AT39	-to pcie_tx_p[10]
set_location_assignment PIN_AU41	-to pcie_tx_p[11]
set_location_assignment PIN_AN41	-to pcie_tx_p[12]
set_location_assignment PIN_AL41	-to pcie_tx_p[13]
set_location_assignment PIN_AJ41	-to pcie_tx_p[14]
set_location_assignment PIN_AG41	-to pcie_tx_p[15]
set_location_assignment PIN_AR33	-to plx_fatal_errn
set_location_assignment PIN_AN38	-to plx_i2c_scl0
set_location_assignment PIN_AP39	-to plx_i2c_sda0
set_location_assignment PIN_AU33	-to plx_perstn
set_location_assignment PIN_AR34	-to plx_portgoodn
set_location_assignment PIN_BC37	-to fpga2_cpu_resetn
set_location_assignment PIN_T26		-to fpga2_dipsw[0]
set_location_assignment PIN_V25		-to fpga2_dipsw[1]
set_location_assignment PIN_H25		-to fpga2_dipsw[2]
set_location_assignment PIN_P25		-to fpga2_dipsw[3]
set_location_assignment PIN_G23		-to fpga2_dipsw[4]
set_location_assignment PIN_C22		-to fpga2_dipsw[5]
set_location_assignment PIN_H22		-to fpga2_dipsw[6]
set_location_assignment PIN_T25		-to fpga2_dipsw[7]
set_location_assignment PIN_N22		-to fpga2_led_g[0]
set_location_assignment PIN_AH19	-to fpga2_led_g[1]
set_location_assignment PIN_V27		-to fpga2_led_g[2]
set_location_assignment PIN_F16		-to fpga2_led_g[3]
set_location_assignment PIN_AV13	-to fpga2_led_g[4]
set_location_assignment PIN_AF17	-to fpga2_led_g[5]
set_location_assignment PIN_AJ13	-to fpga2_led_g[6]
set_location_assignment PIN_BC14	-to fpga2_led_g[7]
set_location_assignment PIN_N19		-to fpga2_led_r[0]
set_location_assignment PIN_AH22	-to fpga2_led_r[1]
set_location_assignment PIN_P23		-to fpga2_led_r[2]
set_location_assignment PIN_G16		-to fpga2_led_r[3]
set_location_assignment PIN_AP13	-to fpga2_led_r[4]
set_location_assignment PIN_AR16	-to fpga2_led_r[5]
set_location_assignment PIN_AF13	-to fpga2_led_r[6]
set_location_assignment PIN_BA15	-to fpga2_led_r[7]
set_location_assignment PIN_V26		-to fpga2_pb[0]
set_location_assignment PIN_U27		-to fpga2_pb[1]
set_location_assignment PIN_U26		-to fpga2_pb[2]

# Ground
set_location_assignment PIN_P35		-to rzq_5_2

set_instance_assignment -name IO_STANDARD LVDS			-to clkinbotb_ddr3_n
set_instance_assignment -name IO_STANDARD LVDS			-to clkinbotb_ddr3_p
set_instance_assignment -name IO_STANDARD LVDS			-to clkintopb_ddr3_n
set_instance_assignment -name IO_STANDARD LVDS			-to clkintopb_ddr3_p
set_instance_assignment -name IO_STANDARD "2.5 V"		-to clock_scl
set_instance_assignment -name IO_STANDARD "2.5 V"		-to clock_sda
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3e_wen
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dm[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[32]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[33]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[34]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[35]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[36]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[37]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[38]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[39]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[40]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[41]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[42]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[43]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[44]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[45]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[46]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[47]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[48]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[49]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[50]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[51]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[52]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[53]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[54]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[55]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[56]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[57]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[58]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[59]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[60]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[61]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[62]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dq[63]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_n[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_dqs_p[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3f_wen
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3g_wen
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_a[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_casn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_cke
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_clk_p
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_csn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dm[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[32]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[33]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[34]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[35]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[36]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[37]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[38]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[39]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[40]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[41]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[42]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[43]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[44]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[45]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[46]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[47]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[48]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[49]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[50]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[51]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[52]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[53]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[54]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[55]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[56]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[57]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[58]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[59]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[60]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[61]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[62]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dq[63]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_n[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[0]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[1]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[2]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[3]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[4]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[5]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[6]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_dqs_p[7]
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_odt
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_rasn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_resetn
set_instance_assignment -name IO_STANDARD "SSTL-15 CLASS I"	-to ddr3h_wen
set_instance_assignment -name IO_STANDARD "2.5 V"		-to eeprom2_scl
set_instance_assignment -name IO_STANDARD "2.5 V"		-to eeprom2_sda
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[0]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[1]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[2]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[3]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[4]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[5]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[6]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[7]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[8]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[9]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[10]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to c2c_d[11]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_rx_d_n[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_rx_d_n[1]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_rx_d_p[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_rx_d_p[1]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_tx_d_n[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_tx_d_n[1]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_tx_d_p[0]
set_instance_assignment -name IO_STANDARD LVDS			-to fpga2_tx_d_p[1]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to fpga2_cpu_resetn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[2]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[3]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[4]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[5]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[6]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_dipsw[7]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[2]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[3]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[4]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[5]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[6]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_g[7]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[2]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[3]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[4]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[5]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[6]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_led_r[7]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_pb[0]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_pb[1]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to fpga2_pb[2]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_in_n1
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_in_n2
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_in_p1
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_in_p2
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_clk_in0
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_clk_out0
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_out_n1
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_out_n2
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_out_p1
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_clk_out_p2
set_instance_assignment -name IO_STANDARD "1.5 V"		-to hsmc_prsntn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to hsmc_tx_led
set_instance_assignment -name IO_STANDARD "1.5 V"		-to hsmc_rx_led
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_scl
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_sda
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_d[0]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_d[1]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_d[2]
set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_d[3]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[0]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[1]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[2]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[3]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[4]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[5]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[6]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[7]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[8]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[9]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[10]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[11]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[12]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[13]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[14]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[15]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_n[16]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[0]
# UART RX, connected to HSMC_RX_p0 pin of Terasic THDB-HTG board
# set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_rx_d_p[0]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[1]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[2]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[3]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[4]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[5]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[6]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[7]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[8]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[9]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[10]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[11]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[12]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[13]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[14]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[15]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_rx_d_p[16]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[0]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[1]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[2]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[3]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[4]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[5]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[6]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[7]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[8]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[9]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[10]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[11]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[12]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[13]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[14]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[15]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_n[16]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[0]
# UART TX, connected to HSMC_TX_p0 pin of Terasic THDB-HTG board
# set_instance_assignment -name IO_STANDARD "2.5 V"		-to hsmc_tx_d_p[0]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[1]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[2]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[3]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[4]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[5]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[6]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[7]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[8]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[9]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[10]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[11]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[12]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[13]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[14]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[15]
set_instance_assignment -name IO_STANDARD LVDS			-to hsmc_tx_d_p[16]
set_instance_assignment -name IO_STANDARD "1.5 V"		-to max5_clk
set_instance_assignment -name IO_STANDARD "1.5 V"		-to max5_data
set_instance_assignment -name IO_STANDARD "1.5 V"		-to pcie_led_x16
set_instance_assignment -name IO_STANDARD "1.5 V"		-to plx_fatal_errn
set_instance_assignment -name IO_STANDARD "2.5 V"		-to plx_i2c_scl0
set_instance_assignment -name IO_STANDARD "2.5 V"		-to plx_i2c_sda0
set_instance_assignment -name IO_STANDARD "1.5 V"		-to plx_perstn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to plx_portgoodn
set_instance_assignment -name IO_STANDARD "1.5 V"		-to rzq_5_2
set_instance_assignment -name IO_STANDARD LVDS			-to svb_clk_125_n
set_instance_assignment -name IO_STANDARD LVDS			-to svb_clk_125_p
set_instance_assignment -name IO_STANDARD "1.5 V"		-to svb_clk_50
set_instance_assignment -name IO_STANDARD LVDS			-to svb_clk_n
set_instance_assignment -name IO_STANDARD LVDS			-to svb_clk_p
set_instance_assignment -name INPUT_TERMINATION DIFFERENTIAL	-to svb_clk_p
set_instance_assignment -name INPUT_TERMINATION DIFFERENTIAL	-to hsmc_clk_in_p2
set_instance_assignment -name INPUT_TERMINATION DIFFERENTIAL	-to hsmc_clk_in_n2
set_instance_assignment -name INPUT_TERMINATION DIFFERENTIAL	-to hsmc_rx_d_p
set_instance_assignment -name INPUT_TERMINATION DIFFERENTIAL	-to hsmc_rx_d_n

# Including default assignments
set_global_assignment -name REVISION_TYPE BASE -family "Stratix V"
set_global_assignment -name TIMEQUEST_MULTICORNER_ANALYSIS ON -family "Stratix V"
set_global_assignment -name TIMEQUEST_REPORT_WORST_CASE_TIMING_PATHS OFF -family "Stratix V"
set_global_assignment -name TIMEQUEST_CCPP_TRADEOFF_TOLERANCE 0 -family "Stratix V"
set_global_assignment -name TDC_CCPP_TRADEOFF_TOLERANCE 30 -family "Stratix V"
set_global_assignment -name TIMEQUEST_DO_CCPP_REMOVAL ON -family "Stratix V"
#set_global_assignment -name TIMEQUEST_SPECTRA_Q OFF -family "Stratix V"
set_global_assignment -name SYNTH_TIMING_DRIVEN_SYNTHESIS ON -family "Stratix V"
set_global_assignment -name SYNCHRONIZATION_REGISTER_CHAIN_LENGTH 3 -family "Stratix V"
set_global_assignment -name SYNTH_RESOURCE_AWARE_INFERENCE_FOR_BLOCK_RAM ON -family "Stratix V"
set_global_assignment -name STRATIXV_CONFIGURATION_SCHEME "PASSIVE SERIAL" -family "Stratix V"
set_global_assignment -name OPTIMIZE_HOLD_TIMING "ALL PATHS" -family "Stratix V"
set_global_assignment -name OPTIMIZE_MULTI_CORNER_TIMING ON -family "Stratix V"
set_global_assignment -name PROGRAMMABLE_POWER_TECHNOLOGY_SETTING AUTOMATIC -family "Stratix V"
set_global_assignment -name AUTO_DELAY_CHAINS ON -family "Stratix V"
#set_global_assignment -name ADVANCED_PHYSICAL_OPTIMIZATION ON -family "Stratix V"
set_global_assignment -name ENABLE_OCT_DONE OFF -family "Stratix V"

set_instance_assignment -name PARTITION_HIERARCHY root_partition -to | -section_id Top
